import type { HejbroInput } from "../../../../src/index";
import { bigint, integer, table, text } from "../../../../src/index";
import { app } from "./declarations";

// Step 0: from empty -- a bare `generated always as identity` and a `by
// default` identity with its one confirmed option (`start with`), plus a
// plain column (`count`) the later steps add/drop identity on.

const withIdentities = table(app, "widgets", {
	id: integer().generatedAlwaysAsIdentity(),
	seq: bigint().generatedByDefaultAsIdentity({ startWith: 1000 }),
	label: text(),
	count: integer(),
});

const fromEmpty: ReadonlyArray<HejbroInput> = [app, withIdentities];

// Step 1: `count` gains an identity -- `set not null` then `add generated
// always as identity`.

const countIdentityAdded = table(app, "widgets", {
	id: integer().generatedAlwaysAsIdentity(),
	seq: bigint().generatedByDefaultAsIdentity({ startWith: 1000 }),
	label: text(),
	count: integer().generatedAlwaysAsIdentity(),
});

const identityAdded: ReadonlyArray<HejbroInput> = [app, countIdentityAdded];

// Step 2: `id` re-kinds from always to by default -- `set generated by
// default`, in place.

const idReKinded = table(app, "widgets", {
	id: integer().generatedByDefaultAsIdentity(),
	seq: bigint().generatedByDefaultAsIdentity({ startWith: 1000 }),
	label: text(),
	count: integer().generatedAlwaysAsIdentity(),
});

const reKinded: ReadonlyArray<HejbroInput> = [app, idReKinded];

// Step 3: `count` loses its identity, back to a plain (nullable) column --
// `drop identity` then `drop not null`.

const countIdentityDropped = table(app, "widgets", {
	id: integer().generatedByDefaultAsIdentity(),
	seq: bigint().generatedByDefaultAsIdentity({ startWith: 1000 }),
	label: text(),
	count: integer(),
});

const identityDropped: ReadonlyArray<HejbroInput> = [app, countIdentityDropped];

export const steps: ReadonlyArray<ReadonlyArray<HejbroInput>> = [
	fromEmpty,
	identityAdded,
	reKinded,
	identityDropped,
];
