import { describe, expect, it } from "vitest";
import { schema } from "../src/dsl/schema";
import { getTableMeta, table } from "../src/dsl/table";
import type { KindChange } from "../src/kind/object-kind";
import { tableKind } from "../src/kinds/table-kind";
import { bigint, integer, text } from "../src/types/column-builder-factories";

const app = schema("app");

const expectSingleChange = (changes: ReadonlyArray<KindChange>): KindChange => {
	if (changes.length !== 1) {
		throw new Error(`expected exactly one change, got ${changes.length}`);
	}
	const [change] = changes;
	if (change === undefined) {
		throw new Error("expected a change");
	}
	return change;
};

/** create-table emit for identity columns (D100) -- both kinds, bare and with the one confirmed option token (`startWith`). */
describe("identity columns — create emit", () => {
	it("renders `generated always as identity`, with NOT NULL materialized", () => {
		const widgets = table(app, "widgets", {
			id: integer().generatedAlwaysAsIdentity(),
			label: text(),
		});
		const next = tableKind.serialize(getTableMeta(widgets));
		const change = expectSingleChange(
			tableKind.diff(null, next, "app.widgets"),
		);
		const [createStatement] = tableKind.emit(change);
		expect(createStatement?.sql).toBe(
			'create table "app"."widgets" (\n\t"id" integer not null generated always as identity,\n\t"label" text\n);',
		);
	});

	it("renders `generated by default as identity (start with 1000)`", () => {
		const widgets = table(app, "widgets", {
			seq: bigint().generatedByDefaultAsIdentity({ startWith: 1000 }),
		});
		const next = tableKind.serialize(getTableMeta(widgets));
		const change = expectSingleChange(
			tableKind.diff(null, next, "app.widgets"),
		);
		const [createStatement] = tableKind.emit(change);
		expect(createStatement?.sql).toBe(
			'create table "app"."widgets" (\n\t"seq" bigint not null generated by default as identity (start with 1000)\n);',
		);
	});

	it("renders every option in canonical order regardless of declaration order, space-separated", () => {
		const widgets = table(app, "widgets", {
			seq: bigint().generatedByDefaultAsIdentity({
				cycle: true,
				cache: 5,
				maxValue: 1000,
				minValue: 1,
				increment: 2,
				startWith: 100,
			}),
		});
		const next = tableKind.serialize(getTableMeta(widgets));
		const change = expectSingleChange(
			tableKind.diff(null, next, "app.widgets"),
		);
		const [createStatement] = tableKind.emit(change);
		expect(createStatement?.sql).toBe(
			'create table "app"."widgets" (\n\t"seq" bigint not null generated by default as identity (start with 100 increment by 2 minvalue 1 maxvalue 1000 cache 5 cycle)\n);',
		);
	});

	it("renders `cycle: false` as an explicit `no cycle`", () => {
		const widgets = table(app, "widgets", {
			seq: bigint().generatedByDefaultAsIdentity({ cycle: false }),
		});
		const next = tableKind.serialize(getTableMeta(widgets));
		const change = expectSingleChange(
			tableKind.diff(null, next, "app.widgets"),
		);
		const [createStatement] = tableKind.emit(change);
		expect(createStatement?.sql).toBe(
			'create table "app"."widgets" (\n\t"seq" bigint not null generated by default as identity (no cycle)\n);',
		);
	});
});
