import { describe, expect, it } from "vitest";
import { schema } from "../src/dsl/schema";
import { getTableMeta, table } from "../src/dsl/table";
import { sql } from "../src/expr/sql-template";
import type { KindChange } from "../src/kind/object-kind";
import { tableKind } from "../src/kinds/table-kind";
import { bigint, integer, text } from "../src/types/column-builder-factories";

const app = schema("app");

const expectSingleChange = (changes: ReadonlyArray<KindChange>): KindChange => {
	if (changes.length !== 1) {
		throw new Error(`expected exactly one change, got ${changes.length}`);
	}
	const [change] = changes;
	if (change === undefined) {
		throw new Error("expected a change");
	}
	return change;
};

const emitSql = (
	previousTable: ReturnType<typeof table>,
	nextTable: ReturnType<typeof table>,
): ReadonlyArray<string> => {
	const previous = tableKind.serialize(getTableMeta(previousTable));
	const next = tableKind.serialize(getTableMeta(nextTable));
	const change = expectSingleChange(
		tableKind.diff(previous, next, "app.widgets"),
	);
	return tableKind.emit(change).map((s) => s.sql);
};

describe("identity columns — diff/emit", () => {
	it("identity added: `set not null` before `add generated always as identity` (Postgres rejects identity on a nullable column)", () => {
		const before = table(app, "widgets", { id: integer() });
		const after = table(app, "widgets", {
			id: integer().generatedAlwaysAsIdentity(),
		});
		expect(emitSql(before, after)).toEqual([
			'alter table "app"."widgets" alter column "id" set not null;',
			'alter table "app"."widgets" alter column "id" add generated always as identity;',
		]);
	});

	it("identity added with an option: `add generated by default as identity (start with 1000)`", () => {
		const before = table(app, "widgets", { seq: bigint() });
		const after = table(app, "widgets", {
			seq: bigint().generatedByDefaultAsIdentity({ startWith: 1000 }),
		});
		expect(emitSql(before, after)).toEqual([
			'alter table "app"."widgets" alter column "seq" set not null;',
			'alter table "app"."widgets" alter column "seq" add generated by default as identity (start with 1000);',
		]);
	});

	it("identity removed and the column becomes nullable: `drop identity` before `drop not null` (Postgres rejects dropping not null while identity is set)", () => {
		const before = table(app, "widgets", {
			id: integer().generatedAlwaysAsIdentity(),
		});
		const after = table(app, "widgets", { id: integer() });
		expect(emitSql(before, after)).toEqual([
			'alter table "app"."widgets" alter column "id" drop identity;',
			'alter table "app"."widgets" alter column "id" drop not null;',
		]);
	});

	it("identity removed but the column stays NOT NULL (declared explicitly): only `drop identity`", () => {
		const before = table(app, "widgets", {
			id: integer().generatedAlwaysAsIdentity(),
		});
		const after = table(app, "widgets", { id: integer().notNull() });
		expect(emitSql(before, after)).toEqual([
			'alter table "app"."widgets" alter column "id" drop identity;',
		]);
	});

	it("kind change (always -> by default): `set generated by default`, no not-null statement (both kinds already imply it)", () => {
		const before = table(app, "widgets", {
			id: integer().generatedAlwaysAsIdentity(),
		});
		const after = table(app, "widgets", {
			id: integer().generatedByDefaultAsIdentity(),
		});
		expect(emitSql(before, after)).toEqual([
			'alter table "app"."widgets" alter column "id" set generated by default;',
		]);
	});

	it("kind change (by default -> always): `set generated always`", () => {
		const before = table(app, "widgets", {
			id: integer().generatedByDefaultAsIdentity(),
		});
		const after = table(app, "widgets", {
			id: integer().generatedAlwaysAsIdentity(),
		});
		expect(emitSql(before, after)).toEqual([
			'alter table "app"."widgets" alter column "id" set generated always;',
		]);
	});

	it("a plain column becoming generated is rejected, naming the column with a two-generate-run remedy", () => {
		const before = table(app, "widgets", { total: text() });
		const after = table(app, "widgets", {
			total: text().generatedAlwaysAs(sql`'x'`),
		});
		const previous = tableKind.serialize(getTableMeta(before));
		const next = tableKind.serialize(getTableMeta(after));
		const change = expectSingleChange(
			tableKind.diff(previous, next, "app.widgets"),
		);
		expect(() => tableKind.emit(change)).toThrowError(
			expect.objectContaining({
				code: "unsupported-column-alter",
				message: expect.stringContaining('"total"'),
			}),
		);
	});
});
