import { throwHejbroError } from "../error";

/**
 * Every name an unquoted plpgsql local (row scalars, function args,
 * `new`/`old` and their fields) cannot carry (dual quoting policy, spec
 * §5.3 decision A3), from three sources:
 *
 * 1. `pg_get_keywords()` categories `R` (reserved), `T` (reserved, usable
 *    as a function or type name), and `C` (usable as a column label, but
 *    not as an argument name or a body local — measured on
 *    `postgres:17.11`, design.md's Measurement (1.1)).
 * 2. a variable plpgsql declares on its own: `found`, the exception
 *    block's `sqlstate`/`sqlerrm`, a trigger body's `new` and `old`, and
 *    a trigger function's twelve `tg_*` variables.
 * 3. sixteen words plpgsql opens its own statements with, named one by
 *    one because the keyword table does not carry them — the list is
 *    what defines this source, not a broader "plpgsql statement syntax"
 *    description, since most of plpgsql's own vocabulary renders fine:
 *    eleven fail as a local (`begin`, `by`, `declare`, `execute`,
 *    `foreach`, `if`, `loop`, `next`, `query`, `strict`, `while` —
 *    `return next`/`return query` are plpgsql's own SETOF-returning
 *    statements, so an argument or loop named `next`/`query` renders
 *    `return next;`/`return query;` and either fails at creation
 *    (non-SETOF) or returns the wrong thing) and five stand without
 *    failing but are refused on the same footing (`exception`, `get`,
 *    `perform`, `raise`, `return`) — this change only widens refusal, so
 *    a name already refused stays refused even where it is measured
 *    harmless. Nineteen more of plpgsql's own words are the same family
 *    but measured harmless in every rendered position and stay out of
 *    the class (`exit`, `elsif`, `elseif`, `continue`, `assert`, `open`,
 *    `move`, `close`, `call`, `set`, `reset`, `commit`, `rollback`,
 *    `alias`, `constant`, `reverse`, `slice`, `diagnostics`, `stacked`):
 *    they have never been refused, so leaving them out relaxes nothing,
 *    and refusing them would refuse a working program.
 *
 * Where the failure lands varies by name and by position — a keyword
 * breaks at creation, at an assignment, or at a read; a shadowed name is
 * created silently and read wrong — so every one of them is refused
 * here under one code, at the one place every failure is visible:
 * declaration time, regardless of where in the body the name is
 * measured to actually fail.
 */
export const reservedPlpgsqlNames: ReadonlySet<string> = new Set([
	"all",
	"analyse",
	"analyze",
	"and",
	"any",
	"array",
	"as",
	"asc",
	"asymmetric",
	"authorization",
	"begin",
	"between",
	"bigint",
	"binary",
	"bit",
	"boolean",
	"both",
	"by",
	"case",
	"cast",
	"char",
	"character",
	"check",
	"coalesce",
	"collate",
	"collation",
	"column",
	"concurrently",
	"constraint",
	"create",
	"cross",
	"current_catalog",
	"current_date",
	"current_role",
	"current_schema",
	"current_time",
	"current_timestamp",
	"current_user",
	"dec",
	"decimal",
	"declare",
	"default",
	"deferrable",
	"desc",
	"distinct",
	"do",
	"else",
	"end",
	"except",
	"exception",
	"execute",
	"exists",
	"extract",
	"false",
	"fetch",
	"float",
	"for",
	"foreach",
	"foreign",
	"found",
	"freeze",
	"from",
	"full",
	"get",
	"grant",
	"greatest",
	"group",
	"grouping",
	"having",
	"if",
	"ilike",
	"in",
	"initially",
	"inner",
	"inout",
	"int",
	"integer",
	"intersect",
	"interval",
	"into",
	"is",
	"isnull",
	"join",
	"json",
	"json_array",
	"json_arrayagg",
	"json_exists",
	"json_object",
	"json_objectagg",
	"json_query",
	"json_scalar",
	"json_serialize",
	"json_table",
	"json_value",
	"lateral",
	"leading",
	"least",
	"left",
	"like",
	"limit",
	"localtime",
	"localtimestamp",
	"loop",
	"merge_action",
	"national",
	"natural",
	"nchar",
	"new",
	"next",
	"none",
	"normalize",
	"not",
	"notnull",
	"null",
	"nullif",
	"numeric",
	"offset",
	"old",
	"on",
	"only",
	"or",
	"order",
	"out",
	"outer",
	"overlaps",
	"overlay",
	"perform",
	"placing",
	"position",
	"precision",
	"primary",
	"query",
	"raise",
	"real",
	"references",
	"return",
	"returning",
	"right",
	"row",
	"select",
	"session_user",
	"setof",
	"similar",
	"smallint",
	"some",
	"sqlerrm",
	"sqlstate",
	"strict",
	"substring",
	"symmetric",
	"system_user",
	"table",
	"tablesample",
	"tg_argv",
	"tg_event",
	"tg_level",
	"tg_name",
	"tg_nargs",
	"tg_op",
	"tg_relid",
	"tg_relname",
	"tg_table_name",
	"tg_table_schema",
	"tg_tag",
	"tg_when",
	"then",
	"time",
	"timestamp",
	"to",
	"trailing",
	"treat",
	"trim",
	"true",
	"union",
	"unique",
	"user",
	"using",
	"values",
	"varchar",
	"variadic",
	"verbose",
	"when",
	"where",
	"while",
	"window",
	"with",
	"xmlattributes",
	"xmlconcat",
	"xmlelement",
	"xmlexists",
	"xmlforest",
	"xmlnamespaces",
	"xmlparse",
	"xmlpi",
	"xmlroot",
	"xmlserialize",
	"xmltable",
]);

/**
 * Throws `reserved-local-name` if `name` collides with a name Postgres
 * reserves or plpgsql declares itself — the comparison folds case first,
 * since an unquoted identifier folds to lower case the same way when
 * Postgres resolves it.
 */
export const assertValidLocalName = (
	name: string,
	identity: string,
	declaredAt: string | null,
): void => {
	if (reservedPlpgsqlNames.has(name.toLowerCase())) {
		throwHejbroError(
			"reserved-local-name",
			`local name "${name}" in ${identity} collides with a name Postgres reserves or plpgsql declares itself (a reserved keyword, or a variable such as found or tg_op) — a local by that name fails in the body or silently changes what the name means. Next: rename it.`,
			declaredAt,
		);
	}
};
