import { throwHejbroError } from "../error";

/**
 * Every name an unquoted plpgsql local (row scalars, function args,
 * `new`/`old` and their fields) cannot carry (dual quoting policy, spec
 * §5.3 decision A3), defined by source, not by how it fails: a name
 * Postgres reserves — its keyword table's categories `R` (reserved) and
 * `T` (reserved, usable as a function or type name) — or plpgsql
 * reserves for its own statements; and a variable plpgsql declares on
 * its own (`FOUND`, the exception-block `SQLSTATE`/`SQLERRM`, a trigger
 * function's `TG_*` variables, and `current_schema` among the category-T
 * keywords, which Postgres creates without complaint and reads as the
 * local). Where the failure lands varies by name — a reserved keyword
 * breaks at creation, at an assignment, or at a read, depending on its
 * category, while a shadowed name is created silently and read wrong —
 * so every one of them is refused here under one code, at the one place
 * every failure is visible: declaration time.
 */
export const reservedPlpgsqlNames: ReadonlySet<string> = new Set([
	"all",
	"analyse",
	"analyze",
	"and",
	"any",
	"array",
	"as",
	"asc",
	"asymmetric",
	"authorization",
	"begin",
	"between",
	"binary",
	"both",
	"by",
	"case",
	"cast",
	"check",
	"collate",
	"collation",
	"column",
	"concurrently",
	"constraint",
	"create",
	"cross",
	"current_catalog",
	"current_date",
	"current_role",
	"current_schema",
	"current_time",
	"current_timestamp",
	"current_user",
	"declare",
	"default",
	"deferrable",
	"desc",
	"distinct",
	"do",
	"else",
	"end",
	"except",
	"exception",
	"execute",
	"exists",
	"false",
	"fetch",
	"for",
	"foreach",
	"foreign",
	"found",
	"freeze",
	"from",
	"full",
	"get",
	"grant",
	"group",
	"having",
	"if",
	"ilike",
	"in",
	"initially",
	"inner",
	"intersect",
	"into",
	"is",
	"isnull",
	"join",
	"lateral",
	"leading",
	"left",
	"like",
	"limit",
	"localtime",
	"localtimestamp",
	"loop",
	"natural",
	"new",
	"not",
	"notnull",
	"null",
	"offset",
	"old",
	"on",
	"only",
	"or",
	"order",
	"outer",
	"overlaps",
	"perform",
	"placing",
	"primary",
	"raise",
	"references",
	"return",
	"returning",
	"right",
	"select",
	"session_user",
	"similar",
	"some",
	"sqlerrm",
	"sqlstate",
	"strict",
	"symmetric",
	"system_user",
	"table",
	"tablesample",
	"tg_argv",
	"tg_event",
	"tg_level",
	"tg_name",
	"tg_nargs",
	"tg_op",
	"tg_relid",
	"tg_relname",
	"tg_table_name",
	"tg_table_schema",
	"tg_tag",
	"tg_when",
	"then",
	"to",
	"trailing",
	"true",
	"union",
	"unique",
	"user",
	"using",
	"variadic",
	"verbose",
	"when",
	"where",
	"while",
	"window",
	"with",
]);

/**
 * Throws `reserved-local-name` if `name` collides with a name Postgres
 * reserves or plpgsql declares itself — the comparison folds case first,
 * since an unquoted identifier folds to lower case the same way when
 * Postgres resolves it.
 */
export const assertValidLocalName = (
	name: string,
	identity: string,
	declaredAt: string | null,
): void => {
	if (reservedPlpgsqlNames.has(name.toLowerCase())) {
		throwHejbroError(
			"reserved-local-name",
			`local name "${name}" in ${identity} collides with a name Postgres reserves or plpgsql declares itself (a reserved keyword, or a variable such as found or tg_op) — a local by that name fails in the body or silently changes what the name means. Next: rename it.`,
			declaredAt,
		);
	}
};
