import { throwHejbroError } from "../error";

/**
 * Two classes of name an unquoted plpgsql local (row scalars, function
 * args, `new`/`old` and their fields) cannot carry (dual quoting policy,
 * spec §5.3 decision A3): a keyword Postgres or plpgsql fully reserves,
 * which fails to parse; and a variable plpgsql declares on its own
 * (`FOUND`, the exception-block `SQLSTATE`/`SQLERRM`, and a trigger
 * function's `TG_*` variables) — which parses and creates, then silently
 * resolves to the user's own name instead of plpgsql's, since nothing
 * about a successful `CREATE FUNCTION` reveals the shadowing. Both fail
 * the same way here, under one code, since the earliest place to catch
 * either is the same: declaration time.
 */
export const reservedPlpgsqlNames: ReadonlySet<string> = new Set([
	"all",
	"analyse",
	"analyze",
	"and",
	"any",
	"array",
	"as",
	"asc",
	"asymmetric",
	"begin",
	"between",
	"both",
	"by",
	"case",
	"cast",
	"check",
	"collate",
	"column",
	"constraint",
	"create",
	"current_catalog",
	"current_date",
	"current_role",
	"current_time",
	"current_timestamp",
	"current_user",
	"declare",
	"default",
	"deferrable",
	"desc",
	"distinct",
	"do",
	"else",
	"end",
	"except",
	"exception",
	"execute",
	"exists",
	"false",
	"fetch",
	"for",
	"foreach",
	"foreign",
	"found",
	"from",
	"get",
	"grant",
	"group",
	"having",
	"if",
	"in",
	"initially",
	"intersect",
	"into",
	"lateral",
	"leading",
	"limit",
	"localtime",
	"localtimestamp",
	"loop",
	"new",
	"not",
	"null",
	"offset",
	"old",
	"on",
	"only",
	"or",
	"order",
	"perform",
	"placing",
	"primary",
	"raise",
	"references",
	"return",
	"returning",
	"select",
	"session_user",
	"some",
	"sqlerrm",
	"sqlstate",
	"strict",
	"symmetric",
	"system_user",
	"table",
	"tg_argv",
	"tg_event",
	"tg_level",
	"tg_name",
	"tg_nargs",
	"tg_op",
	"tg_relid",
	"tg_relname",
	"tg_table_name",
	"tg_table_schema",
	"tg_tag",
	"tg_when",
	"then",
	"to",
	"trailing",
	"true",
	"union",
	"unique",
	"user",
	"using",
	"variadic",
	"when",
	"where",
	"while",
	"window",
	"with",
]);

/**
 * Throws `reserved-local-name` if `name` collides with a name plpgsql
 * reserves — the comparison folds case first, since an unquoted
 * identifier folds to lower case the same way when Postgres resolves it.
 */
export const assertValidLocalName = (
	name: string,
	identity: string,
	declaredAt: string | null,
): void => {
	if (reservedPlpgsqlNames.has(name.toLowerCase())) {
		throwHejbroError(
			"reserved-local-name",
			`local name "${name}" in ${identity} collides with a name plpgsql reserves — a keyword, or a variable plpgsql declares itself such as found or tg_op — which cannot be declared unquoted in a function body. Next: rename it.`,
			declaredAt,
		);
	}
};
