import { throwHejbroError } from "../error";
import type { HejbroDeclaration } from "../kind/object-kind";
import type { KindRegistry } from "../kind/registry";
import { compareKeys } from "../sort";
import type { JsonValue } from "./stable-json";
import { stableJson } from "./stable-json";

/**
 * Snapshot format version emitted by this build of hejbro core. Bumped to
 * `2` when `ColumnSnapshot.default` changed shape from a structured
 * `ColumnDefault` object to a rendered SQL expression string (D16,
 * Phase 2 Task 10) — pre-publication, so `parseSnapshot`'s version check
 * is the entire migration story (no compatibility shim).
 */
export const HEJBRO_SNAPSHOT_VERSION = 2;

/** A deterministic, flat representation of every declared database object. */
export type Snapshot = {
	readonly hejbroSnapshot: 2;
	readonly dialect: "postgres";
	/** keyed by `${kind}:${identity}` */
	readonly objects: { readonly [kindAndIdentity: string]: JsonValue };
};

/** The snapshot of an empty database: no declared objects. */
export const emptySnapshot: Snapshot = {
	hejbroSnapshot: HEJBRO_SNAPSHOT_VERSION,
	dialect: "postgres",
	objects: {},
};

type BuiltEntry = {
	readonly key: string;
	readonly node: JsonValue;
	readonly declarationIndex: number;
};

const buildEntry = (
	declaration: HejbroDeclaration,
	declarationIndex: number,
	registry: KindRegistry,
): BuiltEntry => {
	const matchingKinds = registry
		.list()
		.filter((kind) => kind.owns(declaration));
	if (matchingKinds.length === 0) {
		return throwHejbroError(
			"unowned-declaration",
			`declaration at index ${declarationIndex} (declarationKind "${declaration.declarationKind}") is not owned by any registered kind — register a kind whose owns() matches it.`,
		);
	}
	if (matchingKinds.length > 1) {
		return throwHejbroError(
			"ambiguous-declaration",
			`declaration at index ${declarationIndex} (declarationKind "${declaration.declarationKind}") is owned by multiple kinds (${matchingKinds
				.map((kind) => kind.kind)
				.join(", ")}) — kinds must claim disjoint declaration sets.`,
		);
	}
	const [kind] = matchingKinds;
	if (kind === undefined) {
		return throwHejbroError(
			"unowned-declaration",
			`declaration at index ${declarationIndex} matched no kind — this indicates an internal hejbro bug.`,
		);
	}
	const node = kind.serialize(declaration);
	const identity = kind.identify(node);
	return { key: `${kind.kind}:${identity}`, node, declarationIndex };
};

const findDuplicateKey = (
	entries: ReadonlyArray<BuiltEntry>,
): { readonly first: BuiltEntry; readonly second: BuiltEntry } | null => {
	const duplicate = entries.find(
		(entry, entryIndex) =>
			entries.findIndex((other) => other.key === entry.key) !== entryIndex,
	);
	if (duplicate === undefined) {
		return null;
	}
	const first = entries.find((entry) => entry.key === duplicate.key);
	if (first === undefined) {
		return throwHejbroError(
			"duplicate-identity",
			"unreachable — duplicate key had no first occurrence.",
		);
	}
	return { first, second: duplicate };
};

/**
 * Builds a {@link Snapshot} from a flat list of declarations, routing each
 * one to the registered kind whose `owns()` matches it. Throws if a
 * declaration is owned by zero or multiple kinds, or if two declarations
 * produce the same `kind:identity`.
 */
export const buildSnapshot = (
	declarations: ReadonlyArray<HejbroDeclaration>,
	registry: KindRegistry,
): Snapshot => {
	const entries = declarations.map((declaration, declarationIndex) =>
		buildEntry(declaration, declarationIndex, registry),
	);

	const duplicate = findDuplicateKey(entries);
	if (duplicate !== null) {
		return throwHejbroError(
			"duplicate-identity",
			`declarations at index ${duplicate.first.declarationIndex} and index ${duplicate.second.declarationIndex} both produce the identity "${duplicate.first.key}" — rename one of them.`,
		);
	}

	const sortedEntries = [...entries].sort((a, b) => compareKeys(a.key, b.key));
	const objects = Object.fromEntries(
		sortedEntries.map((entry) => [entry.key, entry.node]),
	);

	return {
		hejbroSnapshot: HEJBRO_SNAPSHOT_VERSION,
		dialect: "postgres",
		objects,
	};
};

/** Renders a {@link Snapshot} as deterministic JSON (see {@link stableJson}). */
export const renderSnapshot = (snapshot: Snapshot): string =>
	stableJson(snapshot);

type ParsedSnapshotShape = {
	readonly hejbroSnapshot?: unknown;
	readonly dialect?: unknown;
	readonly objects?: unknown;
};

/**
 * Parses a rendered snapshot back into a {@link Snapshot}, validating its
 * version and shape. A version other than {@link HEJBRO_SNAPSHOT_VERSION}
 * is rejected — most commonly, the snapshot was generated by a newer
 * hejbro than this build.
 */
export const parseSnapshot = (raw: string): Snapshot => {
	const parsed: unknown = JSON.parse(raw);
	if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
		return throwHejbroError(
			"invalid-snapshot",
			"snapshot is not a JSON object — check the file wasn't corrupted or hand-edited incorrectly.",
		);
	}
	const candidate = parsed as ParsedSnapshotShape;
	if (candidate.hejbroSnapshot !== HEJBRO_SNAPSHOT_VERSION) {
		return throwHejbroError(
			"unsupported-snapshot-version",
			`snapshot version ${JSON.stringify(candidate.hejbroSnapshot)} is not supported by this build (expects ${HEJBRO_SNAPSHOT_VERSION}) — it may have been generated by a newer hejbro; upgrade hejbro and try again.`,
		);
	}
	if (candidate.dialect !== "postgres") {
		return throwHejbroError(
			"invalid-snapshot",
			`snapshot dialect ${JSON.stringify(candidate.dialect)} is not supported — only "postgres" is.`,
		);
	}
	if (
		typeof candidate.objects !== "object" ||
		candidate.objects === null ||
		Array.isArray(candidate.objects)
	) {
		return throwHejbroError(
			"invalid-snapshot",
			`snapshot is missing a valid "objects" map — check the file wasn't hand-edited incorrectly.`,
		);
	}
	return {
		hejbroSnapshot: HEJBRO_SNAPSHOT_VERSION,
		dialect: "postgres",
		objects: candidate.objects as Snapshot["objects"],
	};
};
