import type { ColumnBuilder, MutationValue, Table } from "@hejbro/core";

/** Whether a column's `TMeta` declares `notNull: true`, structurally (mirrors `select-result.ts`'s own same-named helper and `column-map.ts`'s infer-from-`ColumnBuilder` pattern, task 3.3). */
type IsColumnNotNull<TColumn extends ColumnBuilder> =
	TColumn extends ColumnBuilder<infer _TFamily, infer TMeta>
		? TMeta extends { readonly notNull: true }
			? true
			: false
		: false;

/** Whether a column's `TMeta` declares `hasDefault: true` (task 3.2/3.16 — `.default()`/`.defaultRandom()`/`.defaultNow()`, or the `serial` family's own implied default, D66). */
type IsColumnHasDefault<TColumn extends ColumnBuilder> =
	TColumn extends ColumnBuilder<infer _TFamily, infer TMeta>
		? TMeta extends { readonly hasDefault: true }
			? true
			: false
		: false;

/**
 * One declared column's mutation-write value type: core's own
 * {@link MutationValue} (harden-query-layer #322's STRICT contract — a
 * matching `Expr`, the `sql` escape hatch, exactly the column's declared
 * read type; `json`/`jsonb`/`bytea` columns have no raw-value arm at
 * all), with the explicit-`null` arm stripped for a `notNull` column:
 * an optional `notNull` column may be *omitted* (a default fills it),
 * but never explicitly written `null`. Reusing `MutationValue` rather
 * than the read-side `ColumnTsType` this file consumed before #337
 * keeps exactly one write-value contract to drift against — the
 * previous parallel shape had already fallen behind the spec (it
 * accepted a raw `jsonb` object and no `Expr` at all).
 */
type InsertColumnValue<TColumn extends ColumnBuilder> =
	IsColumnNotNull<TColumn> extends true
		? Exclude<MutationValue<TColumn>, null>
		: MutationValue<TColumn>;

/**
 * Whether a column is ALWAYS-family (D100 decision 5, #308): a stored
 * generated column (`.generatedAlwaysAs()`, `TMeta.generated: true`) or a
 * `generated always as identity` column (`.generatedAlwaysAsIdentity()`,
 * `TMeta.identity: "always"`) — either way Postgres itself refuses a
 * client-supplied value, so the column gets no key at all in either input
 * type, not even an optional one. A `generated by default as identity`
 * column (`TMeta.identity: "byDefault"`) is deliberately NOT ALWAYS-family:
 * it stays writable, and decision 1's implied `notNull`/`hasDefault` (both
 * identity kinds carry them) already route it through the ordinary
 * `RequiredInsertKeys`/`OptionalInsertKeys` optionality math below with no
 * new branch.
 */
type IsColumnAlwaysGenerated<TColumn extends ColumnBuilder> =
	TColumn extends ColumnBuilder<infer _TFamily, infer TMeta>
		? TMeta extends { readonly generated: true }
			? true
			: TMeta extends { readonly identity: "always" }
				? true
				: false
		: false;

/** Every ALWAYS-family column key (see {@link IsColumnAlwaysGenerated}) — the key set `RequiredInsertKeys`/`OptionalInsertKeys`/{@link UpdateInput} all `Exclude` themselves against, never `never`-value it (the owner rejected that noisier alternative, D100 decision 5). */
type AlwaysGeneratedKeys<TColumns extends Record<string, ColumnBuilder>> = {
	[K in keyof TColumns]: IsColumnAlwaysGenerated<TColumns[K]> extends true
		? K
		: never;
}[keyof TColumns];

/** The declared column keys that MUST appear in an insert row: `notNull` and no default (D8/D3.11's own scope). An ALWAYS-family column (D100 decision 5, #308) is never pulled in here even though it would otherwise read as `notNull`-with-no-ordinary-default — it has no key at all, required or otherwise, because Postgres itself refuses a client-supplied value for it. */
type RequiredInsertKeys<TColumns extends Record<string, ColumnBuilder>> = {
	[K in keyof TColumns]: IsColumnAlwaysGenerated<TColumns[K]> extends true
		? never
		: IsColumnNotNull<TColumns[K]> extends true
			? IsColumnHasDefault<TColumns[K]> extends true
				? never
				: K
			: never;
}[keyof TColumns];

/** Every declared column key that isn't required (D8's `col?: T` convention) and isn't ALWAYS-family — nullable columns, any `notNull` column that also has a default (Postgres fills it in, so omitting it is legal), and a by-default identity column (implied `hasDefault`, decision 1). */
type OptionalInsertKeys<TColumns extends Record<string, ColumnBuilder>> =
	Exclude<
		keyof TColumns,
		RequiredInsertKeys<TColumns> | AlwaysGeneratedKeys<TColumns>
	>;

/**
 * The row shape `insert()` accepts (D1/D3/D8, task 3.11) — a pure type
 * utility over a declared `Table`'s own `TColumns` (task 3.3's own
 * extraction pattern), not yet wired into `insert()`'s actual parameter
 * type (that wiring, like task 3.9's numeric-mode conversion and task
 * 3.10's `select()` return type, is group 4's job; core's own
 * `MutationRow<TTable>` also drops ALWAYS-family keys since #390, but
 * stays family-only on values — this file doesn't touch it).
 *
 * A column is a **required** key only when it's `notNull` *and* has no
 * default (`RequiredInsertKeys`) — Postgres itself would reject an
 * insert omitting such a column, so the type has to reject it too, one
 * key at a time via TypeScript's own excess/missing-property checking
 * on an object literal (no extra logic needed here). Every other
 * declared column is `col?: T` (D8): a `notNull` column *with* a default
 * is optional because Postgres fills it in when omitted, and a nullable
 * column is optional because omitting it and writing `null` to it both
 * mean "no value" — {@link InsertColumnValue} accepts `null` explicitly
 * for exactly that column. An ALWAYS-family column (D100 decision 5,
 * #308) has no key in either half ({@link RequiredInsertKeys}/
 * {@link OptionalInsertKeys} both exclude it), so it never resurfaces
 * here at all.
 */
export type InsertInput<TTable extends Table> =
	TTable extends Table<infer TColumns>
		? {
				[K in RequiredInsertKeys<TColumns>]: InsertColumnValue<TColumns[K]>;
			} & {
				[K in OptionalInsertKeys<TColumns>]?: InsertColumnValue<TColumns[K]>;
			}
		: never;

/**
 * The row shape `update()` accepts (D1/D3, task 3.12) — every declared,
 * non-ALWAYS-family column is optional (D8's `col?: T`), regardless of
 * `notNull`/`hasDefault`: an update only ever touches the columns it
 * names, so `notNull`'s "this column can't be *absent* from a row"
 * guarantee doesn't constrain which keys an update statement supplies.
 * `notNull` still constrains the *value* though — {@link InsertColumnValue}
 * is reused unchanged, so a `notNull` column's value type has no `| null`
 * even though its key is optional: you may leave it out, but you may not
 * explicitly write `null` to it. An ALWAYS-family column (D100 decision 5,
 * #308) has no key here either — an update can no more write a stored
 * generated value or an always-identity value than an insert can — via
 * the same {@link AlwaysGeneratedKeys} exclusion `InsertInput` uses.
 *
 * The trailing `& Record<never, never>` is load-bearing, not decorative:
 * remove it and `UpdateInput<TTable>` stops assigning into core's
 * `MutationRow<TTable>` parameter at `@hejbro/query`'s own chain wiring
 * (#351, `db/chain.ts`, outside this task's file scope) — a single mapped
 * type over a derived key subset doesn't get the generic-assignability
 * pass {@link InsertInput}'s two-mapped-type intersection shape gets. It
 * adds no properties (`Record<never, never>` maps over `never`), so the
 * exclusion above still holds unchanged. A pure type utility over
 * `Table<infer TColumns>` (task 3.3's extraction pattern), not yet wired
 * into `update()`'s actual parameter type (group 4's job, same deferral
 * as {@link InsertInput}).
 */
export type UpdateInput<TTable extends Table> =
	TTable extends Table<infer TColumns>
		? {
				[K in Exclude<
					keyof TColumns,
					AlwaysGeneratedKeys<TColumns>
				>]?: InsertColumnValue<TColumns[K]>;
			} & Record<never, never>
		: never;
