-- hejbro migration
-- + schema app [new]
-- + table app.widgets [new]

create schema "app";

create table "app"."widgets" (
	"id" integer not null generated always as identity,
	"seq" bigint not null generated by default as identity (start with 1000),
	"label" text,
	"count" integer
);