import type { TableSnapshot } from "@hejbro/core";
import type { ExportTableFact } from "../export/description";
import type { ExportPayload } from "../export/write";
import { enumsInSnapshot, tablesInSnapshot } from "./read-snapshot";
import { buildEnumLookup, buildTableEntry, buildTableNameMap } from "./tables";
import { enumUnion } from "./ts-type";

type MatchedTable = {
	readonly table: TableSnapshot;
	readonly fact: ExportTableFact;
};

/** Every exported table fact paired with its own snapshot node — shared
 * by the `Database` interface and the metadata's name map so the two
 * can never disagree about which tables exist. */
const matchedTables = (payload: ExportPayload): ReadonlyArray<MatchedTable> => {
	const tables = tablesInSnapshot(payload.snapshot);
	return payload.tables
		.map((fact) => {
			const table = tables.find(
				(candidate) =>
					candidate.schema === fact.schemaName &&
					candidate.name === fact.tableName,
			);
			if (table === undefined) {
				return null;
			}
			return { table, fact };
		})
		.filter((entry): entry is MatchedTable => entry !== null);
};

/**
 * The point a contract was generated from (schema-vendoring spec, "The
 * contract names the point it was generated from") — `commit` is the
 * git commit `vendor` resolved, `exportHash` is a sha256 of the exact
 * `schema.json` bytes it was read from (the same value `hejbro.lock`
 * records as `schemaHash`, so a check can compare the two without
 * recomputing anything). Neither is a clock, a machine, or a path
 * (Requirement: "The vendored contract is a function of the commit").
 */
export type ContractOrigin = {
	readonly commit: string;
	readonly exportHash: string;
};

const GENERATED_HEADER =
	"// generated by `hejbro vendor` — do not edit by hand.\n";

const renderEnumEntry = (fact: {
	readonly name: string;
	readonly values: ReadonlyArray<string>;
}): string => `\t${JSON.stringify(fact.name)}: ${enumUnion(fact.values)};`;

/**
 * The `Database` interface's own `Views`/`Functions` sections — always
 * present, always empty, in this version: R2-G2's own 2.8 decision
 * carries no view column types and no function signatures in the
 * export, so there is nothing to emit here yet. `Record<string, never>`
 * (never omitting the key entirely) is what tells a reader "not carried
 * by this version" apart from "this schema genuinely has none" — the
 * distinction the delta's own type-layer requirement never promises to
 * make on its own.
 */
const EMPTY_SECTION =
	'\t// R2-G2 2.8: view column types and function signatures are not carried\n\t// by the export yet — this is "not supported", not "none declared".\n\t[key: string]: never;';

/** Renders the `Database` interface's full source (5.1's own settled shape: `Tables`/`Views`/`Functions`/`Enums`, mirroring Supabase's own generated type). */
const renderDatabaseInterface = (
	payload: ExportPayload,
	matched: ReadonlyArray<MatchedTable>,
): string => {
	const snapshot = payload.snapshot;
	const enums = enumsInSnapshot(snapshot);
	const enumLookup = buildEnumLookup(enums);
	const tableEntries = matched
		.map(({ table, fact }) =>
			buildTableEntry(table, fact, snapshot, enumLookup),
		)
		.join("\n");
	const enumEntries = enums.map(renderEnumEntry).join("\n");
	return `export interface Database {
	readonly Tables: {
${tableEntries}
	};
	readonly Views: {
${EMPTY_SECTION}
	};
	readonly Functions: {
${EMPTY_SECTION}
	};
	readonly Enums: {
${enumEntries}
	};
}`;
};

const renderTableNameMapEntry = (matched: MatchedTable): string => {
	const nameMap = buildTableNameMap(matched.table, matched.fact);
	const columns = Object.entries(nameMap.columns)
		.map(
			([tsKey, sqlName]) =>
				`\t\t\t${JSON.stringify(tsKey)}: ${JSON.stringify(sqlName)},`,
		)
		.join("\n");
	return `\t\t${JSON.stringify(nameMap.name)}: {
\t\t\tschema: ${JSON.stringify(nameMap.schema)},
\t\t\tname: ${JSON.stringify(nameMap.name)},
\t\t\tcolumns: {
${columns}
\t\t\t},
\t\t},`;
};

/**
 * The metadata constant (5.6/5.7/5.8) — the origin stamp
 * ({@link ContractOrigin}), the role list the schema declares
 * (Requirement: "Role names travel with the contract"), and a runtime
 * name map per table (planner-confirmed, 5.1 follow-up): a client needs
 * the SQL identity behind every TS key to build a query at all, and
 * without it here it would have to read `schema.json` at runtime,
 * breaking the "import one file" surface the contract exists to give.
 * Carries no value-conversion policy (numeric mode, …) — additive once
 * R2-G6 reveals what it actually needs. A consumer passes
 * `contractMetadata.roles` explicitly to opt into them; holding a
 * contract never adopts a role silently.
 */
const renderMetadata = (
	origin: ContractOrigin,
	roles: ReadonlyArray<string>,
	matched: ReadonlyArray<MatchedTable>,
): string => {
	const tables = matched.map(renderTableNameMapEntry).join("\n");
	return `export const contractMetadata = {
\tcommit: ${JSON.stringify(origin.commit)},
\texportHash: ${JSON.stringify(origin.exportHash)},
\troles: [${roles.map((role) => JSON.stringify(role)).join(", ")}] as const,
\ttables: {
${tables}
\t},
} as const;`;
};

/**
 * The factory (5.6) — binds `Database` inside the generated module, so
 * no type parameter reaches the caller (proposal.md, "the generic
 * binding is done inside the generated module; no type parameter
 * reaches the user"). Its *body* is a placeholder: `@hejbro/query`'s
 * name-keyed client (R2-G6) doesn't exist yet, and nothing this group's
 * own delta requires — every schema-vendoring scenario about the
 * contract is a static-type or metadata property, never a runtime query
 * — needs it to work before then. R2-G6's own 6.11 is the load-and-run
 * proof; wiring a real client body is that group's own task, not a
 * rewrite of this file's shape.
 */
const CREATE_DB_FACTORY = `export const createDb = (conn: unknown): never => {
\tthrow new Error(
\t\t"createDb has no client to bind yet — the name-keyed query client ships in a later hejbro release.",
\t);
};`;

/**
 * The contract file's full source (5.1's settled layout: one file,
 * `.hejbro/vendor/contract.ts`, alongside `schema.json`/`snapshot.sql`).
 * A pure function of `payload` and `origin` — two calls with the same
 * inputs produce byte-identical text (Requirement: "The vendored
 * contract is a function of the commit"); no clock, no machine name, no
 * path reaches it.
 */
export const emitContract = (
	payload: ExportPayload,
	origin: ContractOrigin,
): string => {
	const matched = matchedTables(payload);
	return `${GENERATED_HEADER}
${renderDatabaseInterface(payload, matched)}

${renderMetadata(origin, payload.roles, matched)}

${CREATE_DB_FACTORY}
`;
};
