import type { ExportPayload } from "../export/write";
import type { FunctionClientMeta, FunctionComputation } from "./functions";
import {
	buildFunctionClientMeta,
	computeFunctions,
	renderFunctionEntry,
} from "./functions";
import type { ContractEnumFact } from "./read-snapshot";
import { enumsInSnapshot, tablesInSnapshot } from "./read-snapshot";
import type { TableClientMeta, TableComputation } from "./tables";
import {
	buildEnumLookup,
	buildTableClientMeta,
	computeTable,
	renderTableEntry,
} from "./tables";
import { enumUnion } from "./ts-type";

type EnumLookup = (schema: string, name: string) => ContractEnumFact | null;

/**
 * Every exported table fact computed exactly once (6.1's condition ②) —
 * `renderDatabaseInterface` and `renderMetadata` both render from this
 * same array, so the `Database` interface and `contractMetadata.tables`
 * can never disagree about which tables exist or what either carries. A
 * table fact with no matching snapshot node is dropped, not guessed at.
 * `enumLookup` is built once by the caller and passed in (extended by
 * #587 to `computeFunctions` too), never rebuilt here, for the same
 * "exactly once" reason.
 */
const computeTables = (
	payload: ExportPayload,
	enumLookup: EnumLookup,
): ReadonlyArray<TableComputation> => {
	const snapshot = payload.snapshot;
	const tables = tablesInSnapshot(snapshot);
	return payload.tables
		.map((fact) => {
			const table = tables.find(
				(candidate) =>
					candidate.schema === fact.schemaName &&
					candidate.name === fact.tableName,
			);
			if (table === undefined) {
				return null;
			}
			return computeTable(table, fact, snapshot, enumLookup);
		})
		.filter((entry): entry is TableComputation => entry !== null);
};

/**
 * The point a contract was generated from (schema-vendoring spec, "The
 * contract names the point it was generated from") — `commit` is the
 * git commit `vendor` resolved, `exportHash` is a sha256 of the exact
 * `schema.json` bytes it was read from (the same value `hejbro.lock`
 * records as `schemaHash`, so a check can compare the two without
 * recomputing anything). Neither is a clock, a machine, or a path
 * (Requirement: "The vendored contract is a function of the commit").
 */
export type ContractOrigin = {
	readonly commit: string;
	readonly exportHash: string;
};

/** The textual mark every vendored `contract.ts` carries (D106 M6) —
 * checked as a substring by `vendor/write.ts`'s own overwrite guard, the
 * same discipline `hejbro.lock`'s `VENDOR_LOCK_MARKER` and `hejbro.json`'s
 * schema check already apply to the other two vendored destinations. */
export const CONTRACT_MARKER = "generated by `hejbro vendor`";

const GENERATED_HEADER = `// ${CONTRACT_MARKER} — do not edit by hand.\nimport type { Driver } from "hejbro";\nimport { createNameKeyedDb } from "hejbro";\n`;

const renderEnumEntry = (fact: {
	readonly name: string;
	readonly values: ReadonlyArray<string>;
}): string => `\t${JSON.stringify(fact.name)}: ${enumUnion(fact.values)};`;

/**
 * The `Database` interface's own `Views` section — always present, always
 * empty, in this version: R2-G2's own 2.8 decision carries no view column
 * types in the export, so there is nothing to emit here yet.
 * `Record<string, never>` (never omitting the key entirely) is what tells
 * a reader "not carried by this version" apart from "this schema
 * genuinely has none".
 */
const VIEWS_EMPTY_SECTION =
	'\t// R2-G2 2.8: view column types are not carried by the export yet — this\n\t// is "not supported", not "none declared".\n\t[key: string]: never;';

/** `{}` when no function carries an export name (#587) — distinct from `Views`' own marker: this schema genuinely exports no function, not "not carried by this version". */
const renderFunctionsSection = (
	functions: ReadonlyArray<FunctionComputation>,
): string => {
	if (functions.length === 0) {
		return "\treadonly Functions: {};";
	}
	const entries = functions.map(renderFunctionEntry).join("\n");
	return `\treadonly Functions: {
${entries}
\t};`;
};

/** Renders the `Database` interface's full source (5.1's own settled shape: `Tables`/`Views`/`Functions`/`Enums`, mirroring Supabase's own generated type). */
const renderDatabaseInterface = (
	payload: ExportPayload,
	tables: ReadonlyArray<TableComputation>,
	functions: ReadonlyArray<FunctionComputation>,
): string => {
	const enums = enumsInSnapshot(payload.snapshot);
	const tableEntries = tables.map(renderTableEntry).join("\n");
	const enumEntries = enums.map(renderEnumEntry).join("\n");
	return `export interface Database {
	readonly Tables: {
${tableEntries}
	};
	readonly Views: {
${VIEWS_EMPTY_SECTION}
	};
${renderFunctionsSection(functions)}
	readonly Enums: {
${enumEntries}
	};
}`;
};

/** `\t\t\texisting: true,\n` for an existing table's meta entry, else `""` (compact, no ternary — mirrors core's own `existingField`-style helpers) — add-unmanaged-objects, 3.1. */
const existingMetaLine = (meta: TableClientMeta): string => {
	if (meta.existing !== true) {
		return "";
	}
	return "\t\t\texisting: true,\n";
};

const renderTableClientMetaEntry = (computation: TableComputation): string => {
	const meta = buildTableClientMeta(computation);
	const columns = Object.entries(meta.columns)
		.map(
			([tsKey, column]) =>
				`\t\t\t\t${JSON.stringify(tsKey)}: { sqlName: ${JSON.stringify(column.sqlName)}, typeNode: ${JSON.stringify(column.typeNode)}, mode: ${JSON.stringify(column.mode)}, notNullElements: ${JSON.stringify(column.notNullElements)} },`,
		)
		.join("\n");
	const foreignKeys = meta.foreignKeys
		.map(
			(fk) =>
				`\t\t\t\t{ name: ${JSON.stringify(fk.name)}, columns: ${JSON.stringify(fk.columns)}, referencesSchema: ${JSON.stringify(fk.referencesSchema)}, referencesTable: ${JSON.stringify(fk.referencesTable)}, referencedColumns: ${JSON.stringify(fk.referencedColumns)} },`,
		)
		.join("\n");
	return `\t\t${JSON.stringify(meta.name)}: {
\t\t\tschema: ${JSON.stringify(meta.schema)},
\t\t\tname: ${JSON.stringify(meta.name)},
\t\t\tcolumns: {
${columns}
\t\t\t},
\t\t\tforeignKeys: [
${foreignKeys}
\t\t\t],
${existingMetaLine(meta)}\t\t},`;
};

const renderFunctionReturnsMetaValue = (
	returns: FunctionClientMeta["returns"],
): string => {
	if (returns.kind === "scalar") {
		return `{ kind: "scalar", typeNode: ${JSON.stringify(returns.typeNode)}, mode: ${JSON.stringify(returns.mode)} }`;
	}
	return `{ kind: "table", schema: ${JSON.stringify(returns.schema)}, name: ${JSON.stringify(returns.name)} }`;
};

const renderFunctionClientMetaEntry = (fn: FunctionComputation): string => {
	const meta = buildFunctionClientMeta(fn);
	const args = meta.args
		.map(
			(arg) =>
				`\t\t\t\t{ key: ${JSON.stringify(arg.key)}, sqlName: ${JSON.stringify(arg.sqlName)}, typeNode: ${JSON.stringify(arg.typeNode)}, mode: ${JSON.stringify(arg.mode)}, notNullElements: ${JSON.stringify(arg.notNullElements)} },`,
		)
		.join("\n");
	return `\t\t${JSON.stringify(fn.exportName)}: {
\t\t\tschema: ${JSON.stringify(meta.schema)},
\t\t\tname: ${JSON.stringify(meta.name)},
\t\t\targs: [
${args}
\t\t\t],
\t\t\treturns: ${renderFunctionReturnsMetaValue(meta.returns)},
\t\t},`;
};

/**
 * The metadata constant (5.6/5.7/5.8, extended by R2-G6 6.1) — the
 * origin stamp ({@link ContractOrigin}), the role list the schema
 * declares (Requirement: "Role names travel with the contract"), and a
 * runtime fact map per table: schema-qualified identity, a TS-key→column-
 * fact map (`sqlName`/`typeNode`/`mode`/`notNullElements` — exactly what
 * `@hejbro/query`'s client needs to reconstruct a real column for query
 * compilation and row conversion, planner condition ④), and foreign keys
 * (for relation-following). Without this a client would have to read
 * `schema.json` at runtime, breaking the "import one file" surface the
 * contract exists to give. A consumer passes `contractMetadata.roles`
 * explicitly to opt into them; holding a contract never adopts a role
 * silently.
 */
const renderMetadata = (
	origin: ContractOrigin,
	roles: ReadonlyArray<string>,
	tables: ReadonlyArray<TableComputation>,
	functions: ReadonlyArray<FunctionComputation>,
): string => {
	const tableEntries = tables.map(renderTableClientMetaEntry).join("\n");
	const functionEntries = functions
		.map(renderFunctionClientMetaEntry)
		.join("\n");
	return `export const contractMetadata = {
\tcommit: ${JSON.stringify(origin.commit)},
\texportHash: ${JSON.stringify(origin.exportHash)},
\troles: [${roles.map((role) => JSON.stringify(role)).join(", ")}] as const,
\ttables: {
${tableEntries}
\t},
\tfunctions: {
${functionEntries}
\t},
} as const;`;
};

/**
 * The factory (5.6, wired for real by R2-G6 6.12) — binds `Database`
 * inside the generated module, so no type parameter reaches the caller
 * (proposal.md, "the generic binding is done inside the generated
 * module; no type parameter reaches the user"): the call site below is
 * the only place `<Database>` is ever written. `createNameKeyedDb` and
 * `Driver` come from `"hejbro"` (this file's own header imports), not
 * `"@hejbro/query"` directly — the consumer already depends on `hejbro`
 * for the CLI, and `hejbro`'s own barrel re-exports `@hejbro/query`'s
 * public surface in full (`packages/cli/src/index.ts`), so a vendored
 * contract never asks a consumer to add a second dependency for the one
 * thing it needs from it.
 */
const CREATE_DB_FACTORY = `export const createDb = (conn: Driver) =>
\tcreateNameKeyedDb<Database>(conn, contractMetadata);`;

/**
 * The contract file's full source (5.1's settled layout: one file,
 * `.hejbro/vendor/contract.ts`, alongside `schema.json`/`snapshot.sql`).
 * A pure function of `payload` and `origin` — two calls with the same
 * inputs produce byte-identical text (Requirement: "The vendored
 * contract is a function of the commit"); no clock, no machine name, no
 * path reaches it.
 */
export const emitContract = (
	payload: ExportPayload,
	origin: ContractOrigin,
): string => {
	const enumLookup = buildEnumLookup(enumsInSnapshot(payload.snapshot));
	const tables = computeTables(payload, enumLookup);
	const functions = computeFunctions(payload, tables, enumLookup);
	return `${GENERATED_HEADER}
${renderDatabaseInterface(payload, tables, functions)}

${renderMetadata(origin, payload.roles, tables, functions)}

${CREATE_DB_FACTORY}
`;
};
