import type { ExportPayload } from "../export/write";
import { enumsInSnapshot, tablesInSnapshot } from "./read-snapshot";
import type { TableComputation } from "./tables";
import {
	buildEnumLookup,
	buildTableClientMeta,
	computeTable,
	renderTableEntry,
} from "./tables";
import { enumUnion } from "./ts-type";

/**
 * Every exported table fact computed exactly once (6.1's condition ②) —
 * `renderDatabaseInterface` and `renderMetadata` both render from this
 * same array, so the `Database` interface and `contractMetadata.tables`
 * can never disagree about which tables exist or what either carries. A
 * table fact with no matching snapshot node is dropped, not guessed at.
 */
const computeTables = (
	payload: ExportPayload,
): ReadonlyArray<TableComputation> => {
	const snapshot = payload.snapshot;
	const tables = tablesInSnapshot(snapshot);
	const enumLookup = buildEnumLookup(enumsInSnapshot(snapshot));
	return payload.tables
		.map((fact) => {
			const table = tables.find(
				(candidate) =>
					candidate.schema === fact.schemaName &&
					candidate.name === fact.tableName,
			);
			if (table === undefined) {
				return null;
			}
			return computeTable(table, fact, snapshot, enumLookup);
		})
		.filter((entry): entry is TableComputation => entry !== null);
};

/**
 * The point a contract was generated from (schema-vendoring spec, "A
 * contract's metadata SHALL name where the contract came from") — a
 * discriminated union (CI-G4-R1-01) rather than an optional-commit
 * shape, so a reader that forgets the database case fails to compile,
 * not at run time. The `"git"` case is `vendor`'s own: `commit` is the
 * git commit it resolved, `exportHash` is a sha256 of the exact
 * `schema.json` bytes it was read from (the same value `hejbro.lock`
 * records as `schemaHash`). The `"database"` case is `pull`'s own:
 * `database` is `current_database()`'s name and `schemas` is the list
 * `pull` read — never the connection string, which carries a secret.
 * Neither case carries a clock, a machine, or a path (Requirement: "The
 * vendored contract is a function of the commit").
 */
export type GitContractOrigin = {
	readonly source: "git";
	readonly commit: string;
	readonly exportHash: string;
};

export type DatabaseContractOrigin = {
	readonly source: "database";
	readonly database: string;
	readonly schemas: ReadonlyArray<string>;
};

export type ContractOrigin = GitContractOrigin | DatabaseContractOrigin;

/** The textual mark every `vendor`-written `contract.ts` carries (D106 M6) —
 * checked as a substring by `vendor/write.ts`'s own overwrite guard, the
 * same discipline `hejbro.lock`'s `VENDOR_LOCK_MARKER` and `hejbro.json`'s
 * schema check already apply to the other two vendored destinations. */
export const CONTRACT_MARKER = "generated by `hejbro vendor`";

/** The same mark's `pull`-written counterpart (CI-G4-R1-01) — `pull`
 * writes to the same destination `vendor` does, so its own overwrite
 * guard must recognize this mark too, or a second `pull` run refuses
 * its own prior output. */
export const PULL_CONTRACT_MARKER = "generated by `hejbro pull`";

const GIT_HEADER = `// ${CONTRACT_MARKER} — do not edit by hand.\nimport type { Driver } from "hejbro";\nimport { createNameKeyedDb } from "hejbro";\n`;

/**
 * `pull`'s own header (schema-vendoring spec: the file SHALL say it was
 * inferred from a database rather than vendored from a schema
 * repository) — two lines, not one: the first carries the overwrite
 * mark and states the source, the second names the consequence (guessed
 * keys/modes) and the way out (`hejbro link`), matching the loss
 * report's own "names the way out" convention elsewhere in this change.
 */
const DATABASE_HEADER = `// ${PULL_CONTRACT_MARKER} — inferred from a database catalog, not vendored from a schema repository. Do not edit by hand.
// Column keys are guessed and modes are approximated from the catalog alone; run \`hejbro link\` to replace this with a schema-repository-backed contract.
import type { Driver } from "hejbro";
import { createNameKeyedDb } from "hejbro";
`;

const renderHeader = (origin: ContractOrigin): string => {
	if (origin.source === "git") {
		return GIT_HEADER;
	}
	return DATABASE_HEADER;
};

const renderEnumEntry = (fact: {
	readonly name: string;
	readonly values: ReadonlyArray<string>;
}): string => `\t${JSON.stringify(fact.name)}: ${enumUnion(fact.values)};`;

/**
 * The `Database` interface's own `Views`/`Functions` sections — always
 * present, always empty, in this version: R2-G2's own 2.8 decision
 * carries no view column types and no function signatures in the
 * export, so there is nothing to emit here yet. `Record<string, never>`
 * (never omitting the key entirely) is what tells a reader "not carried
 * by this version" apart from "this schema genuinely has none" — the
 * distinction the delta's own type-layer requirement never promises to
 * make on its own.
 */
const EMPTY_SECTION =
	'\t// R2-G2 2.8: view column types and function signatures are not carried\n\t// by the export yet — this is "not supported", not "none declared".\n\t[key: string]: never;';

/** Renders the `Database` interface's full source (5.1's own settled shape: `Tables`/`Views`/`Functions`/`Enums`, mirroring Supabase's own generated type). */
const renderDatabaseInterface = (
	payload: ExportPayload,
	tables: ReadonlyArray<TableComputation>,
): string => {
	const enums = enumsInSnapshot(payload.snapshot);
	const tableEntries = tables.map(renderTableEntry).join("\n");
	const enumEntries = enums.map(renderEnumEntry).join("\n");
	return `export interface Database {
	readonly Tables: {
${tableEntries}
	};
	readonly Views: {
${EMPTY_SECTION}
	};
	readonly Functions: {
${EMPTY_SECTION}
	};
	readonly Enums: {
${enumEntries}
	};
}`;
};

const renderTableClientMetaEntry = (computation: TableComputation): string => {
	const meta = buildTableClientMeta(computation);
	const columns = Object.entries(meta.columns)
		.map(
			([tsKey, column]) =>
				`\t\t\t\t${JSON.stringify(tsKey)}: { sqlName: ${JSON.stringify(column.sqlName)}, typeNode: ${JSON.stringify(column.typeNode)}, mode: ${JSON.stringify(column.mode)}, notNullElements: ${JSON.stringify(column.notNullElements)} },`,
		)
		.join("\n");
	const foreignKeys = meta.foreignKeys
		.map(
			(fk) =>
				`\t\t\t\t{ name: ${JSON.stringify(fk.name)}, columns: ${JSON.stringify(fk.columns)}, referencesSchema: ${JSON.stringify(fk.referencesSchema)}, referencesTable: ${JSON.stringify(fk.referencesTable)}, referencedColumns: ${JSON.stringify(fk.referencedColumns)} },`,
		)
		.join("\n");
	return `\t\t${JSON.stringify(meta.name)}: {
\t\t\tschema: ${JSON.stringify(meta.schema)},
\t\t\tname: ${JSON.stringify(meta.name)},
\t\t\tcolumns: {
${columns}
\t\t\t},
\t\t\tforeignKeys: [
${foreignKeys}
\t\t\t],
\t\t},`;
};

/**
 * The metadata constant (5.6/5.7/5.8, extended by R2-G6 6.1) — the
 * origin stamp ({@link ContractOrigin}), the role list the schema
 * declares (Requirement: "Role names travel with the contract"), and a
 * runtime fact map per table: schema-qualified identity, a TS-key→column-
 * fact map (`sqlName`/`typeNode`/`mode`/`notNullElements` — exactly what
 * `@hejbro/query`'s client needs to reconstruct a real column for query
 * compilation and row conversion, planner condition ④), and foreign keys
 * (for relation-following). Without this a client would have to read
 * `schema.json` at runtime, breaking the "import one file" surface the
 * contract exists to give. A consumer passes `contractMetadata.roles`
 * explicitly to opt into them; holding a contract never adopts a role
 * silently.
 */
/**
 * The origin fields alone, in the exact position they have always sat
 * (first, inside `contractMetadata`) -- the git branch is required to
 * change by exactly one inserted line versus the pre-union shape
 * (`source: "git",`), never reordered or reformatted (CI-G4-R1-01
 * condition (a), proved by `contract-origin.test.ts`'s own golden).
 * `schemas` is sorted here, not trusted from the caller, so the
 * contract's own determinism (no clock, no machine, and now no catalog
 * row order either) does not depend on `pull` remembering to sort.
 */
const renderOriginFields = (origin: ContractOrigin): string => {
	if (origin.source === "git") {
		return `\tsource: "git",
\tcommit: ${JSON.stringify(origin.commit)},
\texportHash: ${JSON.stringify(origin.exportHash)},`;
	}
	const sortedSchemas = [...origin.schemas].sort();
	return `\tsource: "database",
\tdatabase: ${JSON.stringify(origin.database)},
\tschemas: [${sortedSchemas.map((name) => JSON.stringify(name)).join(", ")}],`;
};

const renderMetadata = (
	origin: ContractOrigin,
	roles: ReadonlyArray<string>,
	tables: ReadonlyArray<TableComputation>,
): string => {
	const tableEntries = tables.map(renderTableClientMetaEntry).join("\n");
	return `export const contractMetadata = {
${renderOriginFields(origin)}
\troles: [${roles.map((role) => JSON.stringify(role)).join(", ")}] as const,
\ttables: {
${tableEntries}
\t},
} as const;`;
};

/**
 * The factory (5.6, wired for real by R2-G6 6.12) — binds `Database`
 * inside the generated module, so no type parameter reaches the caller
 * (proposal.md, "the generic binding is done inside the generated
 * module; no type parameter reaches the user"): the call site below is
 * the only place `<Database>` is ever written. `createNameKeyedDb` and
 * `Driver` come from `"hejbro"` (this file's own header imports), not
 * `"@hejbro/query"` directly — the consumer already depends on `hejbro`
 * for the CLI, and `hejbro`'s own barrel re-exports `@hejbro/query`'s
 * public surface in full (`packages/cli/src/index.ts`), so a vendored
 * contract never asks a consumer to add a second dependency for the one
 * thing it needs from it.
 */
const CREATE_DB_FACTORY = `export const createDb = (conn: Driver) =>
\tcreateNameKeyedDb<Database>(conn, contractMetadata);`;

/**
 * The contract file's full source (5.1's settled layout: one file,
 * `.hejbro/vendor/contract.ts`, alongside `schema.json`/`snapshot.sql`).
 * A pure function of `payload` and `origin` — two calls with the same
 * inputs produce byte-identical text (Requirement: "The vendored
 * contract is a function of the commit"); no clock, no machine name, no
 * path reaches it.
 */
export const emitContract = (
	payload: ExportPayload,
	origin: ContractOrigin,
): string => {
	const tables = computeTables(payload);
	return `${renderHeader(origin)}
${renderDatabaseInterface(payload, tables)}

${renderMetadata(origin, payload.roles, tables)}

${CREATE_DB_FACTORY}
`;
};
