\set ON_ERROR_STOP off
\echo '### C1 window functions at declaration sites'
create table c1 (id int, n int);
\echo '-- C1a column default'
alter table c1 add column d int default row_number() over ();
\echo '-- C1b generated column'
alter table c1 add column g int generated always as (row_number() over ()) stored;
\echo '-- C1c check'
alter table c1 add constraint c1_chk check (row_number() over () > 0);
\echo '-- C1d index expression'
create index c1_ix on c1 ((row_number() over ()));
\echo '-- C1e index predicate'
create index c1_ip on c1 (id) where row_number() over () > 0;
\echo '-- C1f policy using'
create policy c1_p on c1 using (row_number() over () > 0);
\echo '-- C1g policy with check'
create policy c1_q on c1 for insert with check (row_number() over () > 0);

\echo '### C2 scalar function with no return: create then call'
create function c2() returns int language plpgsql as $$ begin perform 1; end $$;
select c2();

\echo '### C3 return query in a non-setof function'
create function c3() returns int language plpgsql as $$ begin return query select 1; end $$;

\echo '### C4 insert ... returning without INTO inside a body'
create table c4 (id serial primary key);
create function c4f() returns void language plpgsql as $$ begin insert into c4 default values returning id; end $$;
select c4f();

\echo '### C5 same statement twice'
create function c5f() returns void language plpgsql as $$ begin insert into c4 default values; insert into c4 default values; end $$;
select c5f(); select count(*) from c4;

\echo '### C6 value-dependent coercions'
create function c6a() returns date language plpgsql as $$ begin return 20260101; end $$;
select c6a();
create function c6b() returns date language plpgsql as $$ begin return 5; end $$;
select c6b();
create function c6c() returns json language plpgsql as $$ begin return '{}'; end $$;
select c6c();
create function c6d() returns int[] language plpgsql as $$ begin return '{}'; end $$;
select c6d();
create function c6e() returns inet language plpgsql as $$ begin return '42.5'; end $$;
select c6e();

\echo '### C7 return query <insert without returning> in a setof function'
create function c7() returns setof c4 language plpgsql as $$ begin return query insert into c4 default values; end $$;
select * from c7();

\echo '### C8 same constraint name on two tables in one schema'
create table c8a (n int constraint shared_chk check (n > 0));
create table c8b (n int constraint shared_chk check (n < 0));
select conname, conrelid::regclass from pg_constraint where conname = 'shared_chk' order by 2;

\echo '### C9 duplicate parameter name'
create function c9(user_id int, user_id int) returns int language sql as $$ select 1 $$;

\echo '### C10 window function in distinct on'
select distinct on (row_number() over (order by id)) id from c1;

\echo '### C11 recursive term: intersect / except / order by / limit / offset'
with recursive r(n) as (select 1 intersect select n+1 from r where n < 3) select * from r;
with recursive r(n) as (select 1 except select n+1 from r where n < 3) select * from r;
with recursive r(n) as (select 1 union all (select n+1 from r where n < 3 order by n)) select * from r;
with recursive r(n) as (select 1 union all (select n+1 from r where n < 3 limit 1)) select * from r;
with recursive r(n) as (select 1 union all (select n+1 from r where n < 3 offset 1)) select * from r;

\echo '### C12 aggregate in the recursive term'
with recursive r(n) as (select 1 union all select max(n)+1 from r where n < 3) select * from r;

\echo '### C13 window function in the recursive term parses'
explain with recursive r(n, w) as (select 1, 1::bigint union all select n+1, row_number() over () from r where n < 3) select * from r;

\echo '### C14 window-only call without over'
select row_number() from c1;

\echo '### C15 recursive term nullable key where the anchor is not null'
create table c15 (id int not null, parent int);
insert into c15 values (1, null), (2, 1);
with recursive t(id, parent) as (select id, parent from c15 where id = 1 union all select c.id, c.parent from c15 c join t on c.parent = t.id) select id, pg_typeof(parent) from t;
with recursive t(v) as (select 1::int union all select null::int from t where false) select pg_typeof(v) from t;

\echo '### C16 identity alters in place; generated expression change; plain to generated'
create table c16 (id int generated by default as identity, a int, g int generated always as (a * 2) stored);
alter table c16 alter column id set generated always;
alter table c16 alter column id set increment by 5;
alter table c16 alter column id drop identity;
alter table c16 alter column id add generated always as identity;
alter table c16 alter column g set expression as (a * 3);
alter table c16 alter column a add generated always as (id) stored;
alter table c16 alter column a set expression as (id);
select version();
