import { schema, table, text, uuid } from "@hejbro/core";
import { describe, expect, it } from "vitest";
import { emitContract } from "../src/contract/emit";
import { buildFixturePayload } from "./support/contract-fixture";

const app = schema("app");

const buildPayload = () => {
	const posts = table(app, "posts", {
		id: uuid().primaryKey().defaultRandom(),
		title: text().notNull(),
	});
	return buildFixturePayload([app, posts]);
};

/**
 * Captured from `emitContract` before `ContractOrigin` became a
 * discriminated union (CI-G4-R1-01, lead condition (a)): the exact bytes
 * a git-sourced contract produced when `origin` was still the bare
 * `{commit, exportHash}` shape. `renderOrigin`'s git branch must widen
 * to this text plus exactly one inserted line (`source: "git",`) --
 * never reformat, reorder, or touch anything else. Reproduced here as a
 * transform of itself (insert one line before `commit:`) rather than a
 * second hand-typed copy, so a transcription slip can't hide a real
 * regression from this test.
 */
// Captured from the emitter with the origin line removed. Refreshed at the
// dev merge-in of #655 (the Functions section), so the capture carries that
// section too; the assertion below still proves the origin key is the only
// difference between this text and a git-sourced emission.
const PRE_UNION_GIT_GOLDEN = `// generated by \`hejbro vendor\` — do not edit by hand.
import type { Driver } from "hejbro";
import { createNameKeyedDb } from "hejbro";

export interface Database {
	readonly Tables: {
	"posts": {
		readonly Row: {
		readonly id: string;
		readonly title: string;
		};
		readonly Insert: {
		readonly id?: string;
		readonly title: string;
		};
		readonly Update: {
		readonly id?: string;
		readonly title?: string;
		};
		readonly Relationships: readonly [];
	};
	};
	readonly Views: {
	// R2-G2 2.8: view column types are not carried by the export yet — this
	// is "not supported", not "none declared".
	[key: string]: never;
	};
	readonly Functions: {};
	readonly Enums: {

	};
}

export const contractMetadata = {
	commit: "abc123",
	exportHash: "sha256:deadbeef",
	roles: [] as const,
	tables: {
		"posts": {
			schema: "app",
			name: "posts",
			columns: {
				"id": { sqlName: "id", typeNode: {"typeName":"uuid"}, mode: null, notNullElements: false },
				"title": { sqlName: "title", typeNode: {"typeName":"text"}, mode: null, notNullElements: false },
			},
			foreignKeys: [

			],
		},
	},
	functions: {

	},
} as const;

export const createDb = (conn: Driver) =>
	createNameKeyedDb<Database>(conn, contractMetadata);
`;

describe("ContractOrigin discriminated union / CI-G4-R1-01 condition (a)", () => {
	it("a git-sourced contract's bytes change only by the added source key", () => {
		const expected = PRE_UNION_GIT_GOLDEN.replace(
			'\tcommit: "abc123",',
			'\tsource: "git",\n\tcommit: "abc123",',
		);
		// the replace must actually have matched something, or this test
		// would trivially pass by comparing the golden to itself.
		expect(expected).not.toBe(PRE_UNION_GIT_GOLDEN);

		const source = emitContract(buildPayload(), {
			source: "git",
			commit: "abc123",
			exportHash: "sha256:deadbeef",
		});

		expect(source).toBe(expected);
	});
});

describe("ContractOrigin discriminated union / database origin", () => {
	it("says it was inferred from a database, not vendored, and carries no commit", () => {
		const source = emitContract(buildPayload(), {
			source: "database",
			database: "widgets_db",
			schemas: ["app"],
		});

		expect(source).toContain("inferred from a database");
		expect(source).not.toContain("generated by `hejbro vendor`");
		expect(source).not.toContain("commit:");
		expect(source).toContain('source: "database"');
		expect(source).toContain('database: "widgets_db"');
		expect(source).toContain("hejbro link");
	});

	it("sorts the schemas by name, regardless of the order they were given in", () => {
		const forward = emitContract(buildPayload(), {
			source: "database",
			database: "widgets_db",
			schemas: ["zeta", "alpha"],
		});
		const reversed = emitContract(buildPayload(), {
			source: "database",
			database: "widgets_db",
			schemas: ["alpha", "zeta"],
		});

		expect(forward).toBe(reversed);
		expect(forward).toContain('schemas: ["alpha", "zeta"]');
	});

	it("carries no connection string -- the type has no field for one, and none leaks in through database/schemas", () => {
		const source = emitContract(buildPayload(), {
			source: "database",
			database: "widgets_db",
			schemas: ["app"],
		});

		expect(source).not.toMatch(/postgres(ql)?:\/\//);
	});
});
