import { execFileSync } from "node:child_process";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { pgDriver } from "@hejbro/pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { emitDeclarationFiles } from "../src/declare-emit/emit";
import { inferFromCatalog } from "../src/infer/compose";
import { removeContainer } from "./docker-volumes";
import {
	assertBuiltCli,
	createCliFixtureDir,
	removeCliFixtureDir,
	runCli,
	writeFixtureFile,
} from "./support/cli-runner";

/**
 * 2.1's own named red test (`declare-emit.test.ts`'s live half; the pure
 * golden/collision/determinism half lives in `declare-emit-emit.test.ts`,
 * fast and docker-free): "the emitted source loaded and run through
 * `generateMigration`, its DDL compared object by object against the
 * fixture database's own" -- a golden proves the strings, only running it
 * proves the module. Drives the real, built CLI (`hejbro init`/`generate`,
 * `support/cli-runner.ts`) rather than calling `loadDeclarations`/
 * `generateMigration` in-process: jiti's own module resolution can load a
 * different `@hejbro/core` instance than an in-process call would (see
 * `cli-runner.ts`'s own top comment) -- running the built CLI is how a
 * user actually invokes it, and sidesteps the mismatch entirely.
 */
const IMAGE = process.env.HEJBRO_PG_IMAGE ?? "postgres:17-alpine";
const CONTAINER = `hejbro-cli-declare-emit-${process.pid}`;

const dockerAvailable = (): boolean => {
	try {
		execFileSync("docker", ["info"], { stdio: "ignore" });
		return true;
	} catch {
		return false;
	}
};

const sleep = (ms: number): Promise<void> =>
	new Promise((doResolve) => setTimeout(doResolve, ms));

/** Same two-bootstrap-log race `infer-catalog-read.integration.test.ts` already documents and closes. */
const readyLogLineCount = (): number => {
	const logs = execFileSync("sh", ["-c", `docker logs ${CONTAINER} 2>&1`], {
		encoding: "utf-8",
	});
	return (logs.match(/database system is ready to accept connections/g) ?? [])
		.length;
};

const waitUntilReady = async (attemptsLeft: number): Promise<void> => {
	if (readyLogLineCount() >= 2) {
		return;
	}
	if (attemptsLeft <= 0) {
		throw new Error(
			`postgres in container "${CONTAINER}" never became ready. Next: check \`docker logs ${CONTAINER}\`.`,
		);
	}
	await sleep(300);
	return waitUntilReady(attemptsLeft - 1);
};

const containerPort = (): string => {
	const output = execFileSync("docker", ["port", CONTAINER, "5432/tcp"], {
		encoding: "utf-8",
	});
	const firstLine = (output.trim().split("\n")[0] ?? "").trim();
	const port = firstLine.split(":").at(-1);
	if (port === undefined || port === "") {
		throw new Error(
			`could not parse the host port docker mapped for container "${CONTAINER}" from: ${JSON.stringify(output)}`,
		);
	}
	return port;
};

const psqlFile = (database: string, sql: string): void => {
	execFileSync(
		"docker",
		[
			"exec",
			"-i",
			CONTAINER,
			"psql",
			"-U",
			"postgres",
			"-v",
			"ON_ERROR_STOP=1",
			"-q",
			"-d",
			database,
		],
		{ input: sql, stdio: ["pipe", "ignore", "inherit"] },
	);
};

let hostPort = "";

/**
 * One schema exercising the shapes 2.1's own renderer branches on: an
 * enum column, a by-default identity column, a stored generated column, a
 * serial-owned column, a self-referencing FK, a separate FK with `on
 * delete cascade`, a check constraint, a plain index, a partial unique
 * index, and a descending/nulls-first index column -- plus two
 * independent, differently-named cross-schema cycles (both single-column,
 * no-action FKs on both sides -- exactly the shape that used to crash via
 * `.references()`'s own eager fold, #669, regardless of which side the
 * loader reached first, measured directly with a minimal jiti
 * reproduction). CI-G2-R1-16's rule -- every crossing on a schema-file
 * cycle is a handle, never an import -- makes load order irrelevant to
 * either pair; before that rule, this fixture's own first pair
 * (`declare_probe` <-> `declare_probe_other`) is exactly what crashed
 * with `Cannot read properties of undefined (reading 'id')` (quoted in
 * full in this piece's own history). The second pair (`rev_a`/`rev_z`)
 * guards the same mechanism against a second, independently-named
 * schema pair.
 */
const FIXTURE_DDL = `
	create schema declare_probe;
	create schema declare_probe_other;
	create schema rev_a;
	create schema rev_z;

	create type declare_probe.mood as enum ('happy', 'sad');

	create table declare_probe.parents (
		id bigint generated by default as identity primary key,
		name text not null default 'anon',
		mood declare_probe.mood not null default 'happy',
		parent_id bigint references declare_probe.parents (id),
		full_name text generated always as (name || '!') stored,
		constraint parents_name_check check (length(name) > 0)
	);

	create table declare_probe.children (
		id serial primary key,
		parent_id bigint not null references declare_probe.parents (id) on delete cascade
	);

	create index parents_name_idx on declare_probe.parents (name);
	create unique index parents_active_name_idx on declare_probe.parents (name) where parent_id is null;
	create index parents_id_desc_idx on declare_probe.parents (id desc nulls first);

	-- pair 1: this exact shape (declare_probe.cycle_a <-> declare_probe_other.cycle_b)
	-- is what crashed before CI-G2-R1-16's rule.
	create table declare_probe_other.cycle_b (
		id bigint generated always as identity primary key,
		a_id bigint
	);
	create table declare_probe.cycle_a (
		id bigint generated always as identity primary key,
		b_id bigint not null references declare_probe_other.cycle_b (id)
	);
	alter table declare_probe_other.cycle_b
		add constraint cycle_b_a_id_fkey foreign key (a_id) references declare_probe.cycle_a (id);

	-- pair 2: a second, independently-named cycle (rev_a.item <-> rev_z.item),
	-- guarding the same mechanism against a different schema-name pair.
	create table rev_z.item (
		id bigint generated always as identity primary key,
		a_id bigint
	);
	create table rev_a.item (
		id bigint generated always as identity primary key,
		z_id bigint not null references rev_z.item (id)
	);
	alter table rev_z.item
		add constraint item_a_id_fkey foreign key (a_id) references rev_a.item (id);
`;

beforeAll(async () => {
	if (!dockerAvailable()) {
		throw new Error(
			"declare-emit's live witness needs a running Docker daemon -- `docker info` failed. Next: start Docker and re-run `pnpm --filter hejbro test:integration`.",
		);
	}
	execFileSync(
		"docker",
		[
			"run",
			"-d",
			"--name",
			CONTAINER,
			"-e",
			"POSTGRES_PASSWORD=postgres",
			"-e",
			"POSTGRES_HOST_AUTH_METHOD=trust",
			"-p",
			"127.0.0.1::5432",
			IMAGE,
		],
		{ stdio: "ignore" },
	);
	await waitUntilReady(60);
	hostPort = containerPort();
	psqlFile("postgres", FIXTURE_DDL);
	assertBuiltCli();
}, 120_000);

afterAll(() => {
	removeContainer(CONTAINER);
});

const fixtureUrl = (): string =>
	`postgres://postgres@127.0.0.1:${hostPort}/postgres`;

const CONFIG_SOURCE = `import { defineConfig } from "hejbro";

export default defineConfig({
	entry: ["src/**/*.schema.ts"],
	migrationsDir: "migrations",
	snapshotPath: "hejbro.snapshot.json",
	prefixStrategy: "timestamp",
});
`;

describe("declare-emit / 2.1 live witness", () => {
	it("emits source that, loaded and generated against an empty snapshot, reproduces the fixture database's own snapshot object by object", async () => {
		const driver = pgDriver(fixtureUrl());
		const result = await inferFromCatalog({
			session: driver,
			schemas: ["declare_probe", "declare_probe_other", "rev_a", "rev_z"],
			command: "import",
		});
		await driver.client.end();

		const files = emitDeclarationFiles(result);
		expect(files.length).toBeGreaterThan(0);

		const cwd = await createCliFixtureDir();
		try {
			await writeFixtureFile(cwd, "hejbro.config.ts", CONFIG_SOURCE);
			await Promise.all(
				files.map((file) =>
					writeFixtureFile(
						cwd,
						`src/${file.fileBaseName}.schema.ts`,
						file.source,
					),
				),
			);

			const initResult = await runCli(cwd, ["init"]);
			expect(initResult.exitCode).toBe(0);
			const generateResult = await runCli(cwd, ["generate"]);
			expect(generateResult.exitCode).toBe(0);

			const snapshotContent = await readFile(
				join(cwd, "hejbro.snapshot.json"),
				"utf8",
			);
			const writtenSnapshot = JSON.parse(snapshotContent) as {
				readonly objects: Record<string, unknown>;
			};
			expect(writtenSnapshot.objects).toEqual(result.snapshot.objects);
		} finally {
			await removeCliFixtureDir(cwd);
		}
	}, 60_000);

	it('is deterministic: importing the same database twice writes byte-identical files (cli-commands delta: "a second import writes the same bytes")', async () => {
		const driverA = pgDriver(fixtureUrl());
		const first = await inferFromCatalog({
			session: driverA,
			schemas: ["declare_probe", "declare_probe_other", "rev_a", "rev_z"],
			command: "import",
		});
		await driverA.client.end();

		const driverB = pgDriver(fixtureUrl());
		const second = await inferFromCatalog({
			session: driverB,
			schemas: ["declare_probe", "declare_probe_other", "rev_a", "rev_z"],
			command: "import",
		});
		await driverB.client.end();

		expect(emitDeclarationFiles(first)).toEqual(emitDeclarationFiles(second));
	});
});
