import { execFileSync } from "node:child_process";
import { pgDriver } from "@hejbro/pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { readInferenceCatalog } from "../src/infer/catalog";

/**
 * Group 1's own live proof (CI-G1-R1-04): the unit test
 * (`infer-catalog-read.test.ts`) fixes each query's *shape* against a
 * string-matching fake session, which verifies nothing about SQL syntax
 * or join semantics -- this file is where every one of `INFER_CATALOG_
 * QUERIES` runs against a real server at least once. Never runs under
 * the default `pnpm test`/CI (`vitest.integration.config.ts`'s own
 * include, mirroring `check-live.integration.test.ts`) -- local-only,
 * `pnpm --filter hejbro test:integration`. Owns a purpose-built fixture
 * schema rather than reusing `examples/postgres`'s migration chain
 * (group 5's witness owns that database): one fixture carrying every
 * fact 1.2 reads that the unit test's fake session cannot check --an
 * enum, an identity column with non-default options, a stored
 * generated column, a self-referencing foreign key and a separate one
 * with `on delete cascade`, a check constraint, an expression index, a
 * partial unique index, a GIN index with a non-default operator class,
 * and a descending/nulls-first index column.
 */
const IMAGE = process.env.HEJBRO_PG_IMAGE ?? "postgres:17-alpine";
const CONTAINER = `hejbro-cli-infer-catalog-${process.pid}`;

const dockerAvailable = (): boolean => {
	try {
		execFileSync("docker", ["info"], { stdio: "ignore" });
		return true;
	} catch {
		return false;
	}
};

const sleep = (ms: number): Promise<void> =>
	new Promise((doResolve) => setTimeout(doResolve, ms));

/** Same two-bootstrap-log race `check-live.integration.test.ts` documents and closes -- waiting for the *second* "ready" line, not the first. */
const readyLogLineCount = (): number => {
	const logs = execFileSync("sh", ["-c", `docker logs ${CONTAINER} 2>&1`], {
		encoding: "utf-8",
	});
	return (logs.match(/database system is ready to accept connections/g) ?? [])
		.length;
};

const waitUntilReady = async (attemptsLeft: number): Promise<void> => {
	if (readyLogLineCount() >= 2) {
		return;
	}
	if (attemptsLeft <= 0) {
		throw new Error(
			`postgres in container "${CONTAINER}" never became ready. Next: check \`docker logs ${CONTAINER}\`.`,
		);
	}
	await sleep(300);
	return waitUntilReady(attemptsLeft - 1);
};

const containerPort = (): string => {
	const output = execFileSync("docker", ["port", CONTAINER, "5432/tcp"], {
		encoding: "utf-8",
	});
	const firstLine = (output.trim().split("\n")[0] ?? "").trim();
	const port = firstLine.split(":").at(-1);
	if (port === undefined || port === "") {
		throw new Error(
			`could not parse the host port docker mapped for container "${CONTAINER}" from: ${JSON.stringify(output)}`,
		);
	}
	return port;
};

const psqlFile = (database: string, sql: string): void => {
	execFileSync(
		"docker",
		[
			"exec",
			"-i",
			CONTAINER,
			"psql",
			"-U",
			"postgres",
			"-v",
			"ON_ERROR_STOP=1",
			"-q",
			"-d",
			database,
		],
		{ input: sql, stdio: ["pipe", "ignore", "inherit"] },
	);
};

let hostPort = "";

const FIXTURE_DDL = `
	create schema infer_probe;

	create type infer_probe.mood as enum ('happy', 'sad');

	create table infer_probe.parents (
		id bigint generated by default as identity (start with 5 increment by 2) primary key,
		name text not null default 'anon',
		mood infer_probe.mood not null default 'happy',
		parent_id bigint references infer_probe.parents (id),
		email text,
		metadata jsonb,
		full_name text generated always as (name || '!') stored,
		constraint parents_name_check check (length(name) > 0)
	);

	create table infer_probe.children (
		id bigint generated always as identity primary key,
		parent_id bigint not null references infer_probe.parents (id) on delete cascade
	);

	create index parents_email_lower_idx on infer_probe.parents (lower(email));
	create unique index parents_active_name_idx on infer_probe.parents (name) where parent_id is null;
	create index parents_metadata_gin_idx on infer_probe.parents using gin (metadata jsonb_path_ops);
	create index parents_id_desc_idx on infer_probe.parents (id desc nulls first);
`;

beforeAll(async () => {
	if (!dockerAvailable()) {
		throw new Error(
			"infer-catalog-read's live-witness suite needs a running Docker daemon (Docker Desktop, or colima: `colima start`) -- `docker info` failed. Next: start Docker and re-run `pnpm --filter hejbro test:integration`.",
		);
	}
	execFileSync(
		"docker",
		[
			"run",
			"-d",
			"--name",
			CONTAINER,
			"-e",
			"POSTGRES_PASSWORD=postgres",
			"-e",
			"POSTGRES_HOST_AUTH_METHOD=trust",
			"-p",
			"127.0.0.1::5432",
			IMAGE,
		],
		{ stdio: "ignore" },
	);
	await waitUntilReady(60);
	hostPort = containerPort();
	psqlFile("postgres", FIXTURE_DDL);
}, 120_000);

afterAll(() => {
	execFileSync("docker", ["rm", "-f", CONTAINER], { stdio: "ignore" });
});

const fixtureUrl = (): string =>
	`postgres://postgres@127.0.0.1:${hostPort}/postgres`;

describe("readInferenceCatalog / 1.2b live witness", () => {
	it("reads back exactly what the fixture DDL declared", async () => {
		const driver = pgDriver(fixtureUrl());
		try {
			const catalog = await readInferenceCatalog(driver);

			const idColumn = catalog.columnDetails.find(
				(row) =>
					row.schema === "infer_probe" &&
					row.table === "parents" &&
					row.name === "id",
			);
			expect(idColumn?.identityKind).toBe("d");

			const fullNameColumn = catalog.columnDetails.find(
				(row) =>
					row.schema === "infer_probe" &&
					row.table === "parents" &&
					row.name === "full_name",
			);
			expect(fullNameColumn?.generatedKind).toBe("s");

			const identityOptions = catalog.identitySequenceOptions.find(
				(row) => row.schema === "infer_probe" && row.table === "parents",
			);
			expect(identityOptions?.startValue).toBe("5");
			expect(identityOptions?.increment).toBe("2");

			const selfRefFk = catalog.foreignKeyDetails.find(
				(row) =>
					row.schema === "infer_probe" &&
					row.table === "parents" &&
					row.name.includes("parent_id"),
			);
			expect(selfRefFk?.targetTable).toBe("parents");
			expect(selfRefFk?.targetColumns).toEqual(["id"]);
			expect(selfRefFk?.onDelete).toBe("a");

			const cascadeFk = catalog.foreignKeyDetails.find(
				(row) => row.schema === "infer_probe" && row.table === "children",
			);
			expect(cascadeFk?.targetTable).toBe("parents");
			expect(cascadeFk?.onDelete).toBe("c");

			const checkExpr = catalog.checkExpressions.find(
				(row) => row.name === "parents_name_check",
			);
			expect(checkExpr?.expression).toBe("(length(name) > 0)");

			const exprIndex = catalog.indexDetails.find(
				(row) => row.name === "parents_email_lower_idx",
			);
			expect(exprIndex?.columns).toHaveLength(1);
			expect(exprIndex?.columns[0]?.column).toBeNull();
			// Real Postgres output (verified directly, docker postgres:17-alpine):
			// no cast, since `email` is already `text` and `lower(text)` is a
			// real overload -- confirms pg_get_indexdef needs no `::text` guess.
			expect(exprIndex?.columns[0]?.text).toBe("lower(email)");

			const partialIndex = catalog.indexDetails.find(
				(row) => row.name === "parents_active_name_idx",
			);
			expect(partialIndex?.isUnique).toBe(true);
			expect(partialIndex?.predicate).toBe("(parent_id IS NULL)");

			const ginIndex = catalog.indexDetails.find(
				(row) => row.name === "parents_metadata_gin_idx",
			);
			expect(ginIndex?.method).toBe("gin");
			expect(ginIndex?.columns[0]?.opclass).toBe("jsonb_path_ops");
			expect(ginIndex?.columns[0]?.opclassIsDefault).toBe(false);
			// pg_get_indexdef's per-column form carries no opclass suffix of its
			// own (verified directly: only the whole-index form does) -- this
			// pins that `text` and `opclass` never duplicate the same fact, so
			// 1.4 can safely combine them without re-parsing `text`.
			expect(ginIndex?.columns[0]?.text).toBe("metadata");

			const descIndex = catalog.indexDetails.find(
				(row) => row.name === "parents_id_desc_idx",
			);
			expect(descIndex?.columns[0]?.descending).toBe(true);
			expect(descIndex?.columns[0]?.nullsFirst).toBe(true);
			// Same non-duplication pin as above, for indoption's DESC/NULLS
			// FIRST bits: pg_get_indexdef's per-column form never appends them.
			expect(descIndex?.columns[0]?.text).toBe("id");

			const enumRow = catalog.enumLabels.find(
				(row) => row.schema === "infer_probe" && row.name === "mood",
			);
			expect(enumRow).toBeDefined();
		} finally {
			await driver.client.end();
		}
	});
});
