import { execFileSync } from "node:child_process";
import {
	emptySnapshot,
	generateMigration,
	schema,
	table,
	timestamptz,
} from "@hejbro/core";
import { pgDriver } from "@hejbro/pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { readInferenceCatalog } from "../src/infer/catalog";
import { inferColumnKeys } from "../src/infer/column-keys";
import { inferFromCatalog } from "../src/infer/compose";

/**
 * Group 1's own live proof (CI-G1-R1-04): the unit test
 * (`infer-catalog-read.test.ts`) fixes each query's *shape* against a
 * string-matching fake session, which verifies nothing about SQL syntax
 * or join semantics -- this file is where every one of `INFER_CATALOG_
 * QUERIES` runs against a real server at least once. Never runs under
 * the default `pnpm test`/CI (`vitest.integration.config.ts`'s own
 * include, mirroring `check-live.integration.test.ts`) -- local-only,
 * `pnpm --filter hejbro test:integration`. Owns a purpose-built fixture
 * schema rather than reusing `examples/postgres`'s migration chain
 * (group 5's witness owns that database): one fixture carrying every
 * fact 1.2 reads that the unit test's fake session cannot check --an
 * enum, an identity column with non-default options, a stored
 * generated column, a self-referencing foreign key and a separate one
 * with `on delete cascade`, a check constraint, an expression index, a
 * partial unique index, a GIN index with a non-default operator class,
 * and a descending/nulls-first index column.
 */
const IMAGE = process.env.HEJBRO_PG_IMAGE ?? "postgres:17-alpine";
const CONTAINER = `hejbro-cli-infer-catalog-${process.pid}`;

const dockerAvailable = (): boolean => {
	try {
		execFileSync("docker", ["info"], { stdio: "ignore" });
		return true;
	} catch {
		return false;
	}
};

const sleep = (ms: number): Promise<void> =>
	new Promise((doResolve) => setTimeout(doResolve, ms));

/** Same two-bootstrap-log race `check-live.integration.test.ts` documents and closes -- waiting for the *second* "ready" line, not the first. */
const readyLogLineCount = (): number => {
	const logs = execFileSync("sh", ["-c", `docker logs ${CONTAINER} 2>&1`], {
		encoding: "utf-8",
	});
	return (logs.match(/database system is ready to accept connections/g) ?? [])
		.length;
};

const waitUntilReady = async (attemptsLeft: number): Promise<void> => {
	if (readyLogLineCount() >= 2) {
		return;
	}
	if (attemptsLeft <= 0) {
		throw new Error(
			`postgres in container "${CONTAINER}" never became ready. Next: check \`docker logs ${CONTAINER}\`.`,
		);
	}
	await sleep(300);
	return waitUntilReady(attemptsLeft - 1);
};

const containerPort = (): string => {
	const output = execFileSync("docker", ["port", CONTAINER, "5432/tcp"], {
		encoding: "utf-8",
	});
	const firstLine = (output.trim().split("\n")[0] ?? "").trim();
	const port = firstLine.split(":").at(-1);
	if (port === undefined || port === "") {
		throw new Error(
			`could not parse the host port docker mapped for container "${CONTAINER}" from: ${JSON.stringify(output)}`,
		);
	}
	return port;
};

const psqlFile = (database: string, sql: string): void => {
	execFileSync(
		"docker",
		[
			"exec",
			"-i",
			CONTAINER,
			"psql",
			"-U",
			"postgres",
			"-v",
			"ON_ERROR_STOP=1",
			"-q",
			"-d",
			database,
		],
		{ input: sql, stdio: ["pipe", "ignore", "inherit"] },
	);
};

let hostPort = "";

const FIXTURE_DDL = `
	create schema infer_probe;

	create type infer_probe.mood as enum ('happy', 'sad');

	create table infer_probe.parents (
		id bigint generated by default as identity (start with 5 increment by 2) primary key,
		name text not null default 'anon',
		mood infer_probe.mood not null default 'happy',
		parent_id bigint references infer_probe.parents (id),
		email text,
		metadata jsonb,
		full_name text generated always as (name || '!') stored,
		constraint parents_name_check check (length(name) > 0)
	);

	create table infer_probe.children (
		id bigint generated always as identity primary key,
		parent_id bigint not null references infer_probe.parents (id) on delete cascade
	);

	create index parents_email_lower_idx on infer_probe.parents (lower(email));
	create unique index parents_active_name_idx on infer_probe.parents (name) where parent_id is null;
	create index parents_metadata_gin_idx on infer_probe.parents using gin (metadata jsonb_path_ops);
	create index parents_id_desc_idx on infer_probe.parents (id desc nulls first);

	-- CI-G1-R1-06 (B): a named, composite UNIQUE table constraint -- does
	-- its backing index carry the same name?
	create table infer_probe.pairs (
		a bigint not null,
		b bigint not null,
		constraint pairs_a_b_unique unique (a, b)
	);

	-- CI-G1-R1-06 (C): a quoted, camelCase SQL column name -- what key does
	-- 1.1 infer, and what column name does round-tripping that key through
	-- table()/generateMigration actually produce?
	create table infer_probe.naming_probe (
		"createdAt" timestamptz
	);

	-- CI-G1-R1-16 info: the delta's own "Two SQL names that collide on one
	-- key are both described" scenario -- user_id keeps the plain key
	-- (physical order), "USER_ID" gets the collision suffix, and since
	-- toSnakeCase("userId2") is "user_id2" (not "USER_ID"), the second is
	-- exactly as undeclarable as "createdAt", for a different reason.
	create table infer_probe.collision_probe (
		user_id uuid,
		"USER_ID" uuid
	);

	-- CI-G1-R1-10 (D): the three-way sequence split -- identity-owned
	-- (parents.id/children.id above), serial-owned (legacy.id, deptype
	-- 'a'), and standalone (orphan_seq, no OWNED BY at all, only an
	-- incidental nextval() default with no ownership dependency).
	create sequence infer_probe.orphan_seq;
	create table infer_probe.legacy (
		id serial primary key,
		external_id integer default nextval('infer_probe.orphan_seq')
	);
`;

beforeAll(async () => {
	if (!dockerAvailable()) {
		throw new Error(
			"infer-catalog-read's live-witness suite needs a running Docker daemon (Docker Desktop, or colima: `colima start`) -- `docker info` failed. Next: start Docker and re-run `pnpm --filter hejbro test:integration`.",
		);
	}
	execFileSync(
		"docker",
		[
			"run",
			"-d",
			"--name",
			CONTAINER,
			"-e",
			"POSTGRES_PASSWORD=postgres",
			"-e",
			"POSTGRES_HOST_AUTH_METHOD=trust",
			"-p",
			"127.0.0.1::5432",
			IMAGE,
		],
		{ stdio: "ignore" },
	);
	await waitUntilReady(60);
	hostPort = containerPort();
	psqlFile("postgres", FIXTURE_DDL);
}, 120_000);

afterAll(() => {
	execFileSync("docker", ["rm", "-f", CONTAINER], { stdio: "ignore" });
});

const fixtureUrl = (): string =>
	`postgres://postgres@127.0.0.1:${hostPort}/postgres`;

/**
 * Read once, asserted by many independent `it`s below -- split
 * deliberately (CI-G1-R1-05) so a mutant's failure is isolated to the
 * one `it` whose fact it broke, instead of one giant assertion list
 * where a single early failure hides whether everything after it would
 * have stayed green. `let` at module scope is fine here -- `check:bans`
 * only walks each package's own `src`, never `test` -- mirrors
 * `check-live.integration.test.ts`'s own `let snapshot`.
 */
let catalog: Awaited<ReturnType<typeof readInferenceCatalog>>;
let driver: ReturnType<typeof pgDriver>;

beforeAll(async () => {
	driver = pgDriver(fixtureUrl());
	catalog = await readInferenceCatalog(driver);
});

afterAll(async () => {
	await driver.client.end();
});

describe("readInferenceCatalog / 1.2b live witness", () => {
	it("reads a by-default identity column's kind and non-default options", () => {
		const idColumn = catalog.columnDetails.find(
			(row) =>
				row.schema === "infer_probe" &&
				row.table === "parents" &&
				row.name === "id",
		);
		expect(idColumn?.identityKind).toBe("d");

		const identityOptions = catalog.sequenceOwnership.find(
			(row) =>
				row.schema === "infer_probe" &&
				row.table === "parents" &&
				row.ownership === "i",
		);
		expect(identityOptions?.startValue).toBe("5");
		expect(identityOptions?.increment).toBe("2");
	});

	it("reads a stored generated column's kind", () => {
		const fullNameColumn = catalog.columnDetails.find(
			(row) =>
				row.schema === "infer_probe" &&
				row.table === "parents" &&
				row.name === "full_name",
		);
		expect(fullNameColumn?.generatedKind).toBe("s");
	});

	// children.id is `generated always as identity` with no options at all
	// -- the only fixture column proving "the catalog reports every
	// sequence option regardless" (Postgres always fills seqstart/seqmin/
	// seqmax/etc in from its own defaults once the sequence exists,
	// whether or not the DDL named them). 1.3's "declare only what
	// differs" rule depends on this row actually equalling Postgres's own
	// defaults, which is exactly what this pins.
	it("reads Postgres's own defaults for an identity column with no options named", () => {
		const childIdentityOptions = catalog.sequenceOwnership.find(
			(row) =>
				row.schema === "infer_probe" &&
				row.table === "children" &&
				row.ownership === "i",
		);
		expect(childIdentityOptions).toEqual({
			sequenceSchema: "infer_probe",
			sequenceName: "children_id_seq",
			schema: "infer_probe",
			table: "children",
			column: "id",
			ownership: "i",
			startValue: "1",
			increment: "1",
			minValue: "1",
			maxValue: "9223372036854775807",
			cache: "1",
			cycle: false,
		});
	});

	it("reads a self-referencing foreign key's target and default (unspecified) action", () => {
		const selfRefFk = catalog.foreignKeyDetails.find(
			(row) =>
				row.schema === "infer_probe" &&
				row.table === "parents" &&
				row.name.includes("parent_id"),
		);
		expect(selfRefFk?.targetTable).toBe("parents");
		expect(selfRefFk?.targetColumns).toEqual(["id"]);
		expect(selfRefFk?.onDelete).toBe("a");
	});

	it("reads a foreign key's on-delete-cascade action", () => {
		const cascadeFk = catalog.foreignKeyDetails.find(
			(row) => row.schema === "infer_probe" && row.table === "children",
		);
		expect(cascadeFk?.targetTable).toBe("parents");
		expect(cascadeFk?.onDelete).toBe("c");
	});

	it("reads a check constraint's expression text", () => {
		const checkExpr = catalog.checkExpressions.find(
			(row) => row.name === "parents_name_check",
		);
		expect(checkExpr?.expression).toBe("(length(name) > 0)");
	});

	it("reads an expression index's column as text with no attribute name", () => {
		const exprIndex = catalog.indexDetails.find(
			(row) => row.name === "parents_email_lower_idx",
		);
		expect(exprIndex?.columns).toHaveLength(1);
		expect(exprIndex?.columns[0]?.column).toBeNull();
		// Real Postgres output (verified directly, docker postgres:17-alpine):
		// no cast, since `email` is already `text` and `lower(text)` is a
		// real overload -- confirms pg_get_indexdef needs no `::text` guess.
		expect(exprIndex?.columns[0]?.text).toBe("lower(email)");
	});

	it("reads a partial unique index's predicate", () => {
		const partialIndex = catalog.indexDetails.find(
			(row) => row.name === "parents_active_name_idx",
		);
		expect(partialIndex?.isUnique).toBe(true);
		expect(partialIndex?.predicate).toBe("(parent_id IS NULL)");
	});

	it("reads a GIN index's non-default operator class, without duplicating it in the column text", () => {
		const ginIndex = catalog.indexDetails.find(
			(row) => row.name === "parents_metadata_gin_idx",
		);
		expect(ginIndex?.method).toBe("gin");
		expect(ginIndex?.columns[0]?.opclass).toBe("jsonb_path_ops");
		expect(ginIndex?.columns[0]?.opclassIsDefault).toBe(false);
		// pg_get_indexdef's per-column form carries no opclass suffix of its
		// own (verified directly: only the whole-index form does) -- this
		// pins that `text` and `opclass` never duplicate the same fact, so
		// 1.4 can safely combine them without re-parsing `text`.
		expect(ginIndex?.columns[0]?.text).toBe("metadata");
	});

	it("reads a descending/nulls-first index column, without duplicating it in the column text", () => {
		const descIndex = catalog.indexDetails.find(
			(row) => row.name === "parents_id_desc_idx",
		);
		expect(descIndex?.columns[0]?.descending).toBe(true);
		expect(descIndex?.columns[0]?.nullsFirst).toBe(true);
		// Same non-duplication pin as above, for indoption's DESC/NULLS
		// FIRST bits: pg_get_indexdef's per-column form never appends them.
		expect(descIndex?.columns[0]?.text).toBe("id");
	});

	it("reads an enum type's presence", () => {
		const enumRow = catalog.enumLabels.find(
			(row) => row.schema === "infer_probe" && row.name === "mood",
		);
		expect(enumRow).toBeDefined();
	});

	// CI-G1-R1-10 (D): the three-way split, live -- identity ('i') is
	// already pinned above (parents.id/children.id); this is the other
	// two branches, and the one negative (orphan_seq owns nothing).
	it("reads a serial column's own sequence ownership as 'a', distinct from identity's 'i'", () => {
		const serialOwnership = catalog.sequenceOwnership.find(
			(row) =>
				row.schema === "infer_probe" &&
				row.table === "legacy" &&
				row.column === "id",
		);
		expect(serialOwnership?.ownership).toBe("a");
		expect(serialOwnership?.sequenceName).toBe("legacy_id_seq");
	});

	it("never reports a standalone sequence's incidental nextval() default as ownership", () => {
		// orphan_seq backs external_id's default via a plain nextval() call,
		// never `ALTER SEQUENCE ... OWNED BY` -- no row should name it at
		// all, for any column, at any ownership kind.
		const anyOwnership = catalog.sequenceOwnership.find(
			(row) =>
				row.sequenceSchema === "infer_probe" &&
				row.sequenceName === "orphan_seq",
		);
		expect(anyOwnership).toBeUndefined();
	});

	// CI-G1-R1-06 (B): "a named UNIQUE table constraint's backing index
	// carries the same name" is a claim, not yet evidence -- this measures
	// it against a real server rather than assuming Postgres's own naming
	// convention holds.
	it("observes the same-named backing index for a named composite UNIQUE constraint", () => {
		const uniqueIndex = catalog.indexDetails.find(
			(row) => row.schema === "infer_probe" && row.table === "pairs",
		);
		expect(uniqueIndex?.name).toBe("pairs_a_b_unique");
		expect(uniqueIndex?.isUnique).toBe(true);
		expect(uniqueIndex?.columns.map((column) => column.column)).toEqual([
			"a",
			"b",
		]);
	});

	// CI-G1-R1-06 (C): measurement only, no fix -- what key does 1.1 infer
	// for a quoted camelCase SQL name, and what column name does
	// round-tripping that key through table()/generateMigration actually
	// produce? Report the real strings; do not make this pass by design.
	it("measures the round trip for a quoted camelCase column name", () => {
		const namingColumn = catalog.columnDetails.find(
			(row) => row.schema === "infer_probe" && row.table === "naming_probe",
		);
		// The catalog's own attname preserves the original case exactly --
		// confirms the DDL's quoting was not itself silently lower-cased.
		expect(namingColumn?.name).toBe("createdAt");

		const inferredKey = inferColumnKeys([namingColumn?.name ?? ""])[0] ?? "";
		// Observed, not designed: lower-casing the whole name (1.1's own
		// rule) erases the createdAt/createdat boundary before the
		// "join runs between non-alphanumeric characters" step ever sees
		// it, since there is no non-alphanumeric separator between
		// "created" and "At" to split on.
		expect(inferredKey).toBe("createdat");

		const app = schema("infer_probe_naming_probe");
		// Uses the *inferred* key ("createdat"), not the original SQL name --
		// this is what the real pipeline would actually pass to table().
		const declared = table(app, "naming_probe", {
			[inferredKey]: timestamptz(),
		});
		const migration = generateMigration({
			declarations: [app, declared],
			previousSnapshot: emptySnapshot,
		});
		// Observed, not designed: toSnakeCase("createdat") has no uppercase
		// letter left to split on, so the round trip produces one word,
		// "createdat" -- not the original "createdAt". A declaration
		// generated from this key can never reproduce the source column's
		// exact spelling.
		expect(migration.sql).toContain('"createdat"');
		expect(migration.sql).not.toContain("created_at");
		expect(migration.sql).not.toContain('"createdAt"');
	});
});

describe("inferFromCatalog / 1.8 single entry point", () => {
	// One case pins all three outputs against each other for the same fact
	// (CI-G1-R1-14): a column whose SQL name no declaration key can
	// reproduce ("createdAt") is absent from the snapshot, present in the
	// description, and named in the loss report -- import's own contract.
	it("import: omits an undeclarable-name column from the snapshot, keeps it in the description, and names it in the loss report", async () => {
		const result = await inferFromCatalog({
			session: driver,
			schemas: ["infer_probe"],
			command: "import",
		});

		const namingTable = result.snapshot.objects[
			"table:infer_probe.naming_probe"
		] as { readonly columns: ReadonlyArray<{ readonly name: string }> };
		expect(
			namingTable.columns.some((column) => column.name === "createdat"),
		).toBe(false);

		const describedTable = result.description.tables.find(
			(entry) =>
				entry.schema === "infer_probe" && entry.table === "naming_probe",
		);
		expect(
			describedTable?.columns.some((column) => column.sqlName === "createdAt"),
		).toBe(true);

		expect(result.lossReport.some((line) => line.includes("createdAt"))).toBe(
			true,
		);
	});

	// CI-G1-R1-16: contract/emit.ts's own rule ("a table fact with no
	// matching snapshot node is dropped, not guessed at") means pull's
	// snapshot half must exclude an undeclarable-name column too, or the
	// contract would declare a column under a name the database does not
	// have. Only the loss report's wording differs from import's.
	it("pull: also omits an undeclarable-name column from the snapshot, and names it with its own consequence", async () => {
		const result = await inferFromCatalog({
			session: driver,
			schemas: ["infer_probe"],
			command: "pull",
		});

		const namingTable = result.snapshot.objects[
			"table:infer_probe.naming_probe"
		] as { readonly columns: ReadonlyArray<{ readonly name: string }> };
		expect(
			namingTable.columns.some((column) => column.name === "createdat"),
		).toBe(false);

		const line = result.lossReport.find((entry) => entry.includes("createdAt"));
		expect(line).toBeDefined();
		expect(line).toContain("cannot be carried in the contract");
		expect(line).not.toContain("only partly declared");
	});

	// The delta's own "Two SQL names that collide on one key are both
	// described" scenario (CI-G1-R1-16 info) -- description carries both
	// user_id and "USER_ID", but only the first (physical order, plain
	// key) can round-trip; the loss report names the second.
	it("a collision: both columns are described, but only the earliest-in-physical-order one reaches the snapshot", async () => {
		const result = await inferFromCatalog({
			session: driver,
			schemas: ["infer_probe"],
			command: "pull",
		});

		const described = result.description.tables.find(
			(entry) =>
				entry.schema === "infer_probe" && entry.table === "collision_probe",
		);
		expect(described?.columns).toEqual([
			{ sqlName: "user_id", tsKey: "userId" },
			{ sqlName: "USER_ID", tsKey: "userId2" },
		]);

		const collisionTable = result.snapshot.objects[
			"table:infer_probe.collision_probe"
		] as { readonly columns: ReadonlyArray<{ readonly name: string }> };
		expect(collisionTable.columns.map((column) => column.name)).toEqual([
			"user_id",
		]);

		const collisionLine = result.lossReport.find((entry) =>
			entry.includes("collision_probe"),
		);
		expect(collisionLine).toContain("USER_ID");
		expect(collisionLine).not.toContain('infer_probe.collision_probe.user_id"');
	});
});
