/**
 * #471: the `hejbro` barrel's curation of `@hejbro/core`'s runtime
 * exports. Two lists, never one: every runtime value core exports must
 * appear in exactly one of them, and `test/exports.test.ts` fails the
 * build when a core export is in neither or in both -- so a newcomer has
 * to be classified before it ships (the completeness pattern
 * `.claude/rules/naming.md` prescribes over a bare allowlist). Types are
 * not curated: `index.ts` re-exports every core type wholesale.
 *
 * VOCABULARY is what a schema author or query writer types and is the
 * explicit value re-export list in `index.ts`; ENGINE stays importable
 * from `@hejbro/core` (the interface presets and sibling packages build
 * on) and stops appearing on `hejbro`. The three banner readers are
 * vocabulary because the skill documents them as `hejbro` exports;
 * `leftJoinedBrand` is vocabulary because a shipped spec names it as
 * reaching users through `hejbro`.
 */
/** Runtime values `hejbro` re-exports from `@hejbro/core`. */
export const VOCABULARY = [
	// Declarations
	"check",
	"defineFunction",
	"defineTrigger",
	"defineView",
	"existingTable",
	"grant",
	"index",
	"pgEnum",
	"rls",
	"schema",
	"table",
	// Column types
	"bigint",
	"bigserial",
	"boolean",
	"bytea",
	"char",
	"cidr",
	"date",
	"doublePrecision",
	"inet",
	"integer",
	"interval",
	"json",
	"jsonb",
	"macaddr",
	"numeric",
	"real",
	"serial",
	"smallint",
	"smallserial",
	"text",
	"time",
	"timestamp",
	"timestamptz",
	"timetz",
	"uuid",
	"varchar",
	// Column options and declaration options
	"columnDefault",
	"columnGenerated",
	"columnIdentity",
	"columnNotNull",
	"deferredStatement",
	"foreignKeyActions",
	"indexMethods",
	"predropStatement",
	"roleName",
	// Expressions
	"and",
	"between",
	"coalesce",
	"eq",
	"exists",
	"expr",
	"genRandomUuid",
	"gt",
	"gte",
	"ilike",
	"inArray",
	"isNotNull",
	"isNull",
	"like",
	"literal",
	"lt",
	"lte",
	"ne",
	"not",
	"notBetween",
	"notExists",
	"notIlike",
	"notInArray",
	"notLike",
	"now",
	"op",
	"or",
	"sql",
	"statement",
	// Aggregates and window functions
	"avg",
	"count",
	"cumeDist",
	"denseRank",
	"firstValue",
	"lag",
	"lastValue",
	"lead",
	"max",
	"min",
	"nthValue",
	"ntile",
	"over",
	"percentRank",
	"rank",
	"rowNumber",
	"sum",
	// Query builders
	"asc",
	"deleteFrom",
	"desc",
	"insert",
	"jsonArrayFrom",
	"jsonObjectFrom",
	"select",
	"update",
	"withCte",
	// Banner readers (documented in the generate/verify workflow)
	"parseBannerBaseline",
	"parseBannerHashes",
	"parseBannerUpgradedFrom",
	"parseBannerVersion",
	// User-facing utilities and the one brand a shipped spec names
	"HejbroError",
	"assertNoNulls",
	"leftJoinedBrand",
] as const;

/** Runtime values `@hejbro/core` exports that `hejbro` deliberately does not. */
export const ENGINE = [
	// Renderers
	"renderBanner",
	"renderDelete",
	"renderExpr",
	"renderFunctionSql",
	"renderInsert",
	"renderLiteral",
	"renderMigrationPrefix",
	"renderQuery",
	"renderSelect",
	"renderSelectInto",
	"renderSetOp",
	"renderSnapshot",
	"renderTableBoundExpr",
	"renderTableRef",
	"renderTriggerSql",
	"renderTypeNode",
	"renderUpdate",
	// Codecs, snapshot and banner machinery
	"HEJBRO_SNAPSHOT_VERSION",
	"buildSnapshot",
	"canonicalizeSnapshot",
	"computeColumnOrder",
	"decodeExprNode",
	"decodeQueryNode",
	"emptySnapshot",
	"encodeQueryNode",
	"fnv1aHex",
	"noColumnOrder",
	"parseSnapshot",
	"requiredKeysByKind",
	"rewriteTipSnapshotHash",
	"sameJson",
	"stableJson",
	"upgradeSnapshot",
	// Diff, generate and chain
	"changeOperations",
	"checkChain",
	"diffByKey",
	"diffSnapshots",
	"duplicateVersionFallbackOptions",
	"findDuplicateVersionGroups",
	"generateMigration",
	"generateMigrations",
	"migrationFileName",
	"migrationPrefixStrategies",
	"migrationVersionOf",
	"planDuplicateVersionFix",
	"planRenames",
	// Kinds, registry and presets
	"createColumnBuilder",
	"createDefaultRegistry",
	"createKindRegistry",
	"enumKind",
	"functionKind",
	"grantKind",
	"policyKind",
	"presetValidators",
	"registerPresets",
	"rlsKind",
	"runValidators",
	"schemaKind",
	"sequenceKind",
	"tableKind",
	"triggerKind",
	"viewKind",
	// Expression traversal and rewriting
	"BUILDER_READ_SHAPES",
	"SELECT_CLAUSE_TRAVERSALS",
	"assertSameSetOpKeyOrder",
	"collectColumnRefs",
	"cteRowMeta",
	"existsChildExprs",
	"isCteReference",
	"isExpr",
	"liftLiteral",
	"liftOperand",
	"orderGroupByChain",
	"replaceSelectChildExprs",
	"resolveOrderTerm",
	"selectChildExprs",
	"selectExprChildExprs",
	"someDeepExprNode",
	// Type families and SQL text helpers
	"assertSqlName",
	"canonicalizeInterval",
	"comparisonOperators",
	"deriveExistingTransitionSlug",
	"deriveForeignKeyName",
	"deriveSlug",
	"familyOfTypeNode",
	"isSqlName",
	"qualifyName",
	"quoteIdentifier",
	"quoteStringLiteral",
	"serializeInterval",
	"simpleTypeNames",
	"sqlTypeFamilies",
	"toSnakeCase",
	// Table metadata, brands and diagnostics
	"assertNever",
	"captureDeclarationSite",
	"columnOriginBrand",
	"columnRef",
	"diagnostic",
	"getTableMeta",
	"hejbroError",
	"isTable",
	"nestedReadBrand",
	"readAsBrand",
	"tableIdentity",
	"tableMeta",
	"throwHejbroError",
	"widenedByBrand", // the type layer's carrying mechanism (asRecursive -> ProjectedColumnResult), not a name a schema author or query writer types
] as const;
