/**
 * `hejbro restore`'s own error/guard message text (§6, #130) — every
 * string here is owner-approved verbatim; this module exists purely to
 * keep `restore.ts` itself readable, not to make policy decisions of its
 * own.
 */

export const dirtyWorkingTreeMessage = (): string =>
	"the working tree has uncommitted changes — restore rewrites declaration files from git history, and mixing that with pending edits of your own risks losing them silently. There's no --force override for this, by design. Next: commit or stash your changes (`git status` to check what's pending), then rerun `hejbro restore <n>`.";

const zeroMigrationsRangeMessage = (target: string): string =>
	`restore target "${target}" is out of range — this project has no migrations yet, so there's nothing to restore. Next: run \`hejbro generate\` to create the first migration.`;

const populatedRangeMessage = (target: string, count: number): string =>
	`restore target "${target}" is out of range — this project has ${count} migration(s) (valid range 1–${count}). Next: run \`hejbro history\` to see the valid migration numbers and their commits.`;

/** `target` is the raw `<n>` argv token, kept as given (even if it isn't a valid integer at all — the message quotes exactly what the user typed). */
export const outOfRangeMessage = (target: string, count: number): string => {
	if (count === 0) {
		return zeroMigrationsRangeMessage(target);
	}
	return populatedRangeMessage(target, count);
};

export const stateLostMessage = (
	number: number,
	survivorNumber: number,
	sha: string,
): string =>
	`migration "${number}"'s declaration state doesn't exist in git — it was squashed together with migration ${survivorNumber} into commit ${sha} (only the last of the group survives as a standalone commit). Next: run \`hejbro restore ${survivorNumber}\` for the closest available state, or find migration ${number}'s exact source in the original feature branch/PR diff before it was squashed.`;

export const historyRewrittenMessage = (
	number: number,
	migrationRelativePath: string,
): string =>
	`migration "${number}"'s commit could not be found by hash — history appears to have been rewritten (rebase/force-push) after this migration was recorded. Next: check \`git reflog\` or the original feature branch for a commit whose ${migrationRelativePath} content matches migration ${number}'s banner hash, then restore manually with \`git checkout <sha> -- <entry paths>\`.`;

const mismatchPrefix = (number: number, sha: string): string =>
	`migration "${number}"'s restored declarations load, but re-serializing them doesn't reproduce migration ${number}'s recorded snapshot — something outside the entry glob has likely drifted since commit ${sha}`;

/** `restore-state-mismatch`, candidate files found outside the entry glob that changed in the same commit range. */
export const mismatchWithCandidatesMessage = (
	number: number,
	sha: string,
	candidatePaths: ReadonlyArray<string>,
): string =>
	`${mismatchPrefix(number, sha)}. Next: these files changed in that range and aren't matched by the entry glob — restore them too, then rerun \`hejbro generate\`: \`git checkout ${sha} -- ${candidatePaths.join(" ")}\`.`;

/** `restore-state-mismatch`, no candidate files, and the migration's own banner records the hejbro version it was generated with (#229). */
export const mismatchNoCandidatesWithVersionMessage = (
	number: number,
	sha: string,
	recordedVersion: string,
	currentVersion: string,
	srcRoot: string,
): string =>
	`${mismatchPrefix(number, sha)}, and no changed file outside the entry glob explains it — migration ${number} was generated by hejbro ${recordedVersion}, this build is ${currentVersion}, and a renderer change within the same format version is the likely cause (formatVersion alone doesn't guarantee reproducibility — see #157/D72). Next: compare manually with \`git diff ${sha} HEAD -- ${srcRoot}\`, or check hejbro's CHANGELOG between ${recordedVersion} and ${currentVersion} for a snapshot-rendering change.`;

/** `restore-state-mismatch`, no candidate files, and the migration predates #229's version banner line entirely. */
export const mismatchNoCandidatesNoVersionMessage = (
	number: number,
	sha: string,
	srcRoot: string,
): string =>
	`${mismatchPrefix(number, sha)}, and no changed file outside the entry glob explains it. This migration predates hejbro recording its own version in the banner (#229), so the exact cause can't be pinned down automatically — likely a changed dependency (package.json/lockfile), non-deterministic declaration code, or a hejbro version change with a renderer change within the same format version (formatVersion alone doesn't guarantee reproducibility — see #157/D72). Next: compare manually with \`git diff ${sha} HEAD -- ${srcRoot}\`; if a hejbro/@hejbro/core version change is suspected, check \`git log -p ${sha} -- package.json\` (or your lockfile) around that commit against the version currently installed (\`hejbro --version\`).`;

/** Detects `#229`'s (not-yet-shipped, at time of writing) `-- hejbro: <version>` banner line directly from a migration file's own raw text — no core export needed, since restore only ever asks "does this specific file already carry that line", never anything core-generic. */
const HEJBRO_VERSION_BANNER_LINE = /^-- hejbro: (.+)$/m;

export const recordedHejbroVersion = (fileContent: string): string | null => {
	const match = HEJBRO_VERSION_BANNER_LINE.exec(fileContent);
	if (match === null) {
		return null;
	}
	return match[1] ?? null;
};
