import type { ForeignKeyAction } from "../dsl/table";
import { throwHejbroError } from "../error";
import { qualifyName, quoteIdentifier } from "../sql/identifier";
import { renderTypeNode } from "../types/type-node";
import type {
	CheckSnapshot,
	ColumnSnapshot,
	ForeignKeySnapshot,
	IdentitySnapshot,
	IndexColumnSnapshot,
	IndexSnapshot,
	TableSnapshot,
} from "./table-snapshot";
import {
	checkExpression,
	columnDefault,
	columnGenerated,
	columnIdentity,
	columnNotNull,
	columnPrimaryKey,
	columnUniqueName,
	foreignKeyOnDelete,
	foreignKeyOnUpdate,
	indexColumnDesc,
	indexColumnExpression,
	indexColumnNulls,
	indexColumnOpclass,
	indexMethod,
	indexUnique,
	indexWhere,
	isExpressionIndexColumn,
	tableChecks,
	tablePrimaryKeyName,
} from "./table-snapshot";

/** Splits a `"schema.table"` identity string into its parts. */
export const splitTableIdentity = (
	identity: string,
): { readonly schema: string; readonly table: string } => {
	const dotIndex = identity.indexOf(".");
	if (dotIndex === -1) {
		return throwHejbroError(
			"invalid-table-identity",
			`table identity "${identity}" is missing a schema qualifier ("schema.table").`,
		);
	}
	return {
		schema: identity.slice(0, dotIndex),
		table: identity.slice(dotIndex + 1),
	};
};

const notNullClause = (column: ColumnSnapshot): ReadonlyArray<string> => {
	if (columnNotNull(column)) {
		return ["not null"];
	}
	return [];
};

const defaultClause = (value: string | null): ReadonlyArray<string> => {
	if (value === null) {
		return [];
	}
	return [`default ${value}`];
};

/**
 * Renders `generated always as (<expression>) stored` for a
 * `.generatedAlwaysAs(...)` column, or `[]` for a plain one (D100, design
 * decision 4) — `<expression>` is the declared `sql` fragment's own text
 * verbatim (`columnGenerated`, decode + `renderExpr`, the same accessor
 * path {@link defaultClause}'s `columnDefault` uses), never re-derived or
 * re-parenthesized beyond the grammar's own required wrap. Mutually
 * exclusive with `defaultClause` on any real column (`table()`'s guard 3,
 * `dsl/table.ts`), so their relative order here is never observed on a
 * single column.
 */
const generatedClause = (column: ColumnSnapshot): ReadonlyArray<string> => {
	const expression = columnGenerated(column);
	if (expression === null) {
		return [];
	}
	return [`generated always as (${expression}) stored`];
};

/** `IdentitySnapshot.kind`'s own `generated ... as identity` phrase, shared by create (this file) and add/alter (`table-kind-emit.ts`'s `identityAddStatement`). */
const IDENTITY_KIND_CLAUSE: Readonly<Record<IdentitySnapshot["kind"], string>> =
	{
		always: "generated always as identity",
		"by-default": "generated by default as identity",
	};

/** `IdentitySnapshot.kind`'s own bare keyword (no `generated`/`as identity`), for `set generated <keyword>` (`table-kind-emit.ts`'s `identityKindChangeStatement`). */
export const IDENTITY_KIND_KEYWORD: Readonly<
	Record<IdentitySnapshot["kind"], string>
> = {
	always: "always",
	"by-default": "by default",
};

/** `IdentitySnapshot`'s own option keys (D100/E6), in canonical output order — deterministic, not declaration order. */
export const IDENTITY_OPTION_KEYS: ReadonlyArray<
	keyof Omit<IdentitySnapshot, "kind">
> = ["startWith", "increment", "minValue", "maxValue", "cache", "cycle"];

/** The five numeric identity option keys' own SQL tokens (D100/E6) — every key but `cycle`, which is boolean-valued and rendered separately below. */
const IDENTITY_NUMBER_OPTION_TOKEN: Readonly<
	Record<
		Exclude<keyof Omit<IdentitySnapshot, "kind">, "cycle">,
		(value: number) => string
	>
> = {
	startWith: (value) => `start with ${value}`,
	increment: (value) => `increment by ${value}`,
	minValue: (value) => `minvalue ${value}`,
	maxValue: (value) => `maxvalue ${value}`,
	cache: (value) => `cache ${value}`,
};

/** `cycle`'s own SQL token — `false` renders `no cycle` explicitly (D100/E6). */
const identityCycleToken = (value: boolean): string => {
	if (value) {
		return "cycle";
	}
	return "no cycle";
};

/**
 * One SQL token per identity option key (D100/E6) — Postgres's own
 * `identity_option`/`sequence_option` keywords, lower-cased. An absent
 * key renders nothing (declaration-is-truth, design decision 3).
 * Exported so `table-kind-emit.ts`'s `identityOptionChangeStatements`
 * (2.3, `set <token>`) reuses the identical tokens this file's own create
 * path renders. `value`'s cast is safe by construction: every caller
 * pairs a key with `identity[key]`'s own value, and only `cycle` is ever
 * boolean-valued (checked first).
 */
export const renderIdentityOptionToken = (
	key: keyof Omit<IdentitySnapshot, "kind">,
	value: number | boolean,
): string => {
	if (key === "cycle") {
		return identityCycleToken(value as boolean);
	}
	return IDENTITY_NUMBER_OPTION_TOKEN[key](value as number);
};

/** Every declared option's own token, in canonical order (D100/E6) — `[]` when none are declared. */
export const identityOptionTokens = (
	identity: IdentitySnapshot,
): ReadonlyArray<string> =>
	IDENTITY_OPTION_KEYS.flatMap((key) => {
		const value = identity[key];
		if (value === undefined) {
			return [];
		}
		return [renderIdentityOptionToken(key, value)];
	});

/**
 * An identity's full phrase: its kind's clause, plus `(<option tokens>)`
 * when at least one option is declared — space-separated, no parens at
 * all when none are. Exported so `table-kind-emit.ts`'s
 * `identityAddStatement` (`alter column ... add <phrase>`) reuses the
 * identical text this file's own create path renders.
 */
export const renderIdentityPhrase = (identity: IdentitySnapshot): string => {
	const phrase = IDENTITY_KIND_CLAUSE[identity.kind];
	const tokens = identityOptionTokens(identity);
	if (tokens.length === 0) {
		return phrase;
	}
	return `${phrase} (${tokens.join(" ")})`;
};

/** Renders an identity column's own clause (create path), or `[]` for a non-identity column. */
const identityClause = (column: ColumnSnapshot): ReadonlyArray<string> => {
	const identity = columnIdentity(column);
	if (identity === null) {
		return [];
	}
	return [renderIdentityPhrase(identity)];
};

/**
 * Renders `constraint "<name>" unique` (#24/D68) — named explicitly
 * (rather than a bare `unique` and letting Postgres pick its own default
 * name) so the identifier actually created always matches
 * `ColumnSnapshot.uniqueName`, the name frozen into the snapshot; an
 * implicit dependency on Postgres's own naming convention happening to
 * agree is exactly what D68 records the name to avoid. `columnUniqueName`
 * is only ever absent when `columnUnique` is `false` (paired fields,
 * `uniqueNameField`/`columnUniqueField` in `table-kind.ts`), so the empty
 * case here can't diverge from `columnUnique`'s own.
 */
const uniqueClause = (column: ColumnSnapshot): ReadonlyArray<string> => {
	const name = columnUniqueName(column);
	if (name === null) {
		return [];
	}
	return ["constraint", quoteIdentifier(name), "unique"];
};

/**
 * Renders one column's full definition clause (name, type, not null,
 * default, generated, identity, unique — D100 adds `generated`/`identity`,
 * see {@link generatedClause}/{@link identityClause}). `overrideDefault`
 * (D74), when given, replaces `columnDefault(column)` as the default's SQL
 * text — used for a serial-family column added to an *existing* table
 * (#23): its default lives in a sibling `sequence` change, never
 * `ColumnSnapshot.default` (see `table-kind-emit.ts`'s own `add column`
 * rendering), so the value has to come from outside this column's own
 * snapshot.
 */
export const renderColumnDefinition = (
	column: ColumnSnapshot,
	overrideDefault?: string,
): string =>
	[
		quoteIdentifier(column.name),
		renderTypeNode(column.typeNode),
		...notNullClause(column),
		...defaultClause(overrideDefault ?? columnDefault(column)),
		...generatedClause(column),
		...identityClause(column),
		...uniqueClause(column),
	].join(" ");

/**
 * Renders `constraint "<name>" primary key (...)` (#24/D68) — named
 * explicitly for the same reason {@link uniqueClause} is: the identifier
 * actually created must match `TableSnapshot.primaryKeyName`, the name
 * frozen into the snapshot, rather than relying on Postgres's own default
 * naming convention agreeing by coincidence. `primaryKeyName` is only
 * ever absent when no column has `primaryKey: true` (`primaryKeyNameField`
 * in `table-kind.ts`), matching `primaryKeyColumns.length === 0` below.
 */
const primaryKeyConstraint = (
	snapshot: TableSnapshot,
): ReadonlyArray<string> => {
	const primaryKeyColumns = snapshot.columns
		.filter((column) => columnPrimaryKey(column))
		.map((column) => quoteIdentifier(column.name));
	const name = tablePrimaryKeyName(snapshot);
	if (primaryKeyColumns.length === 0 || name === null) {
		return [];
	}
	return [
		`constraint ${quoteIdentifier(name)} primary key (${primaryKeyColumns.join(", ")})`,
	];
};

const checkConstraintLines = (snapshot: TableSnapshot): ReadonlyArray<string> =>
	tableChecks(snapshot).map(
		(check) =>
			`constraint ${quoteIdentifier(check.name)} check (${checkExpression(check)})`,
	);

/** Renders `create table … (…);` for a table snapshot, columns in declaration order, then table-level constraints (primary key, then CHECKs, D50). */
export const createTableSql = (snapshot: TableSnapshot): string => {
	const bodyLines = [
		...snapshot.columns.map((column) => renderColumnDefinition(column)),
		...primaryKeyConstraint(snapshot),
		...checkConstraintLines(snapshot),
	];
	return `create table ${qualifyName(snapshot.schema, snapshot.name)} (\n\t${bodyLines.join(",\n\t")}\n);`;
};

const uniqueIndexKeyword = (index: IndexSnapshot): string => {
	if (indexUnique(index)) {
		return "unique ";
	}
	return "";
};

/** Renders ` using <method>` for a non-btree access method, or `""` for btree — Postgres' own default, never spelled out (D85, SC-004). */
const usingClause = (index: IndexSnapshot): string => {
	const method = indexMethod(index);
	if (method === "btree") {
		return "";
	}
	return ` using ${method}`;
};

const descKeyword = (column: IndexColumnSnapshot): ReadonlyArray<string> => {
	if (indexColumnDesc(column)) {
		return ["desc"];
	}
	return [];
};

const nullsClause = (column: IndexColumnSnapshot): ReadonlyArray<string> => {
	const nulls = indexColumnNulls(column);
	if (nulls === null) {
		return [];
	}
	return [`nulls ${nulls}`];
};

/** Renders the operator class token (R4) — a bare identifier, unquoted like `using <method>` (D36 restricts it to snake_case, so quoting is never needed). */
const opclassToken = (column: IndexColumnSnapshot): ReadonlyArray<string> => {
	const opclass = indexColumnOpclass(column);
	if (opclass === null) {
		return [];
	}
	return [opclass];
};

/**
 * The column/expression token of one index column's clause: a quoted
 * name, or an expression entry's rendered SQL wrapped in its own
 * parentheses (R5/R9 — via {@link indexColumnExpression}, the same
 * accessor-mediated render `whereClause` uses for `where`, so this
 * module never imports the expression codec directly). Always wrapped,
 * not just when the expression happens to need it: Postgres' own
 * `index_elem` grammar is `column_name | ( a_expr )` — a function call
 * like `lower(email)` is self-delimiting and could skip the wrap, but an
 * operator expression (`data ->> 'status'`, `a || b`) cannot, and
 * Postgres normalizes either form to the same catalog entry / `pg_dump`
 * output, so always wrapping is simpler and correct for every
 * expression this feature can emit (owner decision 2026-08-22, F7 —
 * corrects an earlier no-wrap reading of contracts/sql.md that only
 * happened to work for the function-call examples it showed).
 */
const indexColumnTarget = (column: IndexColumnSnapshot): string => {
	if (isExpressionIndexColumn(column)) {
		return `(${indexColumnExpression(column) ?? ""})`;
	}
	return quoteIdentifier(column.name);
};

/** Renders one index column's clause: name/expression, then its opclass when set, then `desc` when descending, then `nulls first|last` when set (D51/R4/R9 — `"col" <opclass> desc nulls first`). */
const indexColumnSql = (column: IndexColumnSnapshot): string =>
	[
		indexColumnTarget(column),
		...opclassToken(column),
		...descKeyword(column),
		...nullsClause(column),
	].join(" ");

/** Renders ` where <predicate>` for a partial index, or `""` when the index has none (D51). */
const whereClause = (index: IndexSnapshot): string => {
	const predicate = indexWhere(index);
	if (predicate === null) {
		return "";
	}
	return ` where ${predicate}`;
};

/** Renders `create [unique] index "name" on "schema"."table" (…) [where …];`, columns in declared order with their sort direction and nulls placement (D51). */
export const createIndexSql = (
	schema: string,
	tableName: string,
	index: IndexSnapshot,
): string =>
	`create ${uniqueIndexKeyword(index)}index ${quoteIdentifier(index.name)} on ${qualifyName(schema, tableName)}${usingClause(index)} (${index.columns
		.map(indexColumnSql)
		.join(", ")})${whereClause(index)};`;

const foreignKeyActionClause = (
	keyword: "delete" | "update",
	action: ForeignKeyAction | null,
): string => {
	if (action === null) {
		return "";
	}
	return ` on ${keyword} ${action}`;
};

/** Renders `alter table … add constraint … foreign key (…) references … (…) [on delete …] [on update …];`. */
export const addForeignKeyConstraintSql = (
	schema: string,
	tableName: string,
	foreignKey: ForeignKeySnapshot,
): string => {
	const referenced = splitTableIdentity(foreignKey.referencesTable);
	const localColumns = foreignKey.columns
		.map((column) => quoteIdentifier(column))
		.join(", ");
	const referencedColumns = foreignKey.referencesColumns
		.map((column) => quoteIdentifier(column))
		.join(", ");
	return `alter table ${qualifyName(schema, tableName)} add constraint ${quoteIdentifier(foreignKey.name)} foreign key (${localColumns}) references ${qualifyName(
		referenced.schema,
		referenced.table,
	)} (${referencedColumns})${foreignKeyActionClause("delete", foreignKeyOnDelete(foreignKey))}${foreignKeyActionClause("update", foreignKeyOnUpdate(foreignKey))};`;
};

/** Renders `alter table … add constraint "name" check (…);`. */
export const addCheckConstraintSql = (
	schema: string,
	tableName: string,
	check: CheckSnapshot,
): string =>
	`alter table ${qualifyName(schema, tableName)} add constraint ${quoteIdentifier(check.name)} check (${checkExpression(check)});`;

/** Renders `alter table … add constraint "name" primary key (…);` (#24) — the ALTER-time counterpart of `createTableSql`'s inline `primaryKeyConstraint`, used both for a PK added to an existing table and for the add half of a composite PK's partial-drop repair (`table-kind-emit.ts`'s `emitAlter`). */
export const addPrimaryKeyConstraintSql = (
	schema: string,
	tableName: string,
	constraintName: string,
	columnNames: ReadonlyArray<string>,
): string =>
	`alter table ${qualifyName(schema, tableName)} add constraint ${quoteIdentifier(constraintName)} primary key (${columnNames.map(quoteIdentifier).join(", ")});`;

/** Renders `alter table … drop constraint …;` — shared by foreign keys, checks, and primary keys (the constraint namespace is one per table in Postgres). */
export const dropConstraintSql = (
	schema: string,
	tableName: string,
	constraintName: string,
): string =>
	`alter table ${qualifyName(schema, tableName)} drop constraint ${quoteIdentifier(constraintName)};`;
