import type { Table } from "../dsl/table";
import { getTableMeta, toSnakeCase } from "../dsl/table";
import { throwHejbroError } from "../error";
import type {
	ColumnRef,
	Condition,
	DeleteNode,
	Expr,
	ExprNode,
	InsertNode,
	ReturningNode,
	TableRefNode,
	UpdateNode,
} from "../expr/ast";
import { isExpr } from "../expr/ast";
import { noteBuilder } from "../plpgsql/recording-session";
import type {
	BuilderFamily,
	ColumnBuilder,
	ColumnReadType,
} from "../types/column-builder";
import { liftColumnValue } from "./column-value";

/**
 * The type NAMES whose family is {@link UnwritableFamily} — `json`/`jsonb`
 * map to family `"json"`, `bytea` to family `"bytea"` (`expr/type-family.ts`'s
 * `TYPE_NAME_TO_FAMILY`, unchanged).
 *
 * **Tried reusing the type-level `FamilyOfTypeNode` mirror here first**
 * (`expr/type-family.ts`, the type-level mirror of the runtime
 * `familyOfTypeNode`) and confirmed it doesn't fit: `ColumnMeta["element"]`
 * (`column-builder.ts`, task 3.15) only ever carries the element's bare
 * *type name* (a `TypeNode["typeName"]` string), never a full `TypeNode` —
 * by design, so the type-level array mapping doesn't need to carry
 * precision/scale. `FamilyOfTypeNode` needs a real `TypeNode` member to
 * distribute over, and `Extract<TypeNode, { typeName: TElement }>`
 * resolves to `never` for every *simple* type name (`"text"`, `"uuid"`,
 * `"bigint"`, `"json"`, `"bytea"`, …) because `TypeNode`'s own simple-type
 * member is keyed by the *whole* `SimpleTypeName` union, not one member
 * per literal name (confirmed empirically: a scratch probe assigning
 * `FamilyOfTypeNode<Extract<TypeNode, { typeName: "text" }>>` to an
 * impossible target type-checked with zero error, because `never` is
 * assignable to anything) — feeding that `never` back into
 * `IsUnwritableColumn` silently marked *every* array element as
 * unwritable, including `text[]`, which is exactly backwards. This tiny,
 * closed three-name list (`json`/`jsonb` both map to family `json`,
 * `bytea` to family `bytea`) is the element-typeName mirror of the
 * `UnwritableFamily` two-*family* list already above it, not an independent
 * type-name→family table (there is no third table to drift against; both
 * lists trace to the exact same two Postgres types).
 */
type UnwritableElementTypeName = "json" | "jsonb" | "bytea";

/**
 * `true` when a column has no compile-time-lifted raw-scalar write path —
 * either its own family is {@link UnwritableFamily} directly, or it's an
 * `.array()` column whose declared *element* type name is one of
 * {@link UnwritableElementTypeName} (`jsonb().array()`/`bytea().array()`:
 * the array's own family is always `"array"`, per `.array()`'s own return
 * type, so checking `TFamily` alone would let these two slip through —
 * the approved element scope is "every element type with a write path,
 * `json`/`bytea` arrays excluded" exactly like the scalar case).
 */
type IsUnwritableColumn<TColumn extends ColumnBuilder> =
	TColumn extends ColumnBuilder<infer _TFamily, infer TMeta>
		? TMeta extends {
				readonly typeName: "array";
				readonly element: infer TElement;
			}
			? TElement extends UnwritableElementTypeName
				? true
				: false
			: false
		: false;

/**
 * A value accepted for one column of an insert/update row: a matching
 * `Expr`, an `unknown`-family `Expr`, exactly the column's own declared
 * read type ({@link ColumnReadType} — STRICT, #322 Settled Decision 1:
 * each column accepts exactly its declared read type, brand narrowed,
 * mode narrowed, never a sibling mode's or a widened family-only shape),
 * or `null` (unlike comparisons, `null` is a legal write). `json`/`jsonb`/
 * `bytea` columns — scalar OR array-of — have no raw-scalar arm at all,
 * see {@link IsUnwritableColumn}.
 */
export type MutationValue<TColumn extends ColumnBuilder> =
	| Expr<BuilderFamily<TColumn>>
	| Expr<"unknown">
	| (IsUnwritableColumn<TColumn> extends true ? never : ColumnReadType<TColumn>)
	| null;

/**
 * `true` for a column Postgres itself refuses to write: a stored
 * generated column (`TMeta.generated: true`) or a `generated always as
 * identity` column (`TMeta.identity: "always"`). A `generated by default
 * as identity` column is deliberately NOT in this family — Postgres
 * accepts a supplied value for it, so it stays an ordinary defaulted
 * column. Mirrors the query layer's own ALWAYS-family axis (#390).
 */
type IsAlwaysGeneratedColumn<TColumn extends ColumnBuilder> =
	TColumn extends ColumnBuilder<infer _TFamily, infer TMeta>
		? TMeta extends { readonly generated: true }
			? true
			: TMeta extends { readonly identity: "always" }
				? true
				: false
		: false;

/** One insert/update row, keyed by the table's own TypeScript column names — every column is optional (multi-row insert fills missing keys with SQL `default`), except an ALWAYS-family column ({@link IsAlwaysGeneratedColumn}), which has no key at all — absent, not `never`-valued (D100 decision 5; the spec's input-types requirement covers this raw surface too, #390). */
export type MutationRow<TTable extends Table> =
	TTable extends Table<infer TColumns>
		? {
				readonly [K in keyof TColumns as IsAlwaysGeneratedColumn<
					TColumns[K]
				> extends true
					? never
					: K]?: MutationValue<TColumns[K]>;
			}
		: never;

/** A `returning()` projection: aliased expressions, exactly like `select({ alias: expr })` (#293 group 1). */
export type ReturningProjection = Record<string, Expr>;

/**
 * Hides every mutation stage type's (`InsertFinal`/`UpdateFinal`/
 * `DeleteFinal`) type-only `TTable`/`TReturning` marker behind one
 * shared unique symbol (same technique as `dsl/define-function.ts`'s
 * `functionDeclarationBrand`/`dsl/column-builder.ts`'s `columnMetaBrand`,
 * D15/g3 precedent). Never assigned at runtime.
 *
 * **This anchor is not optional polish here — without it, task
 * 4.11-mutation cannot exist at all.** `InsertFinal`'s only real field,
 * `insertQuery: InsertNode`, is a plain runtime AST node that never
 * varies with `TTable`/`TReturning` and never references them, not even
 * recursively through another method the way `ColumnBuilder`'s own chain
 * methods do (`FunctionDeclaration`'s `args`/`returns` were the same
 * story). Without a non-recursive mention, `InsertFinal<A, X>` and
 * `InsertFinal<B, Y>` would be structurally identical for any
 * `A`/`B`/`X`/`Y` and mutually assignable — every `@ts-expect-error`
 * probe below would pass regardless of whether the generics did
 * anything.
 */
const mutationStageBrand: unique symbol = Symbol("hejbro:mutation-stage-meta");

/** One mutation stage's phantom marker value shape — shared by insert/update/delete so the brand's own type is written once. */
type MutationStageMeta<
	TTable extends Table,
	TReturning extends ReturningProjection | undefined,
> = {
	readonly table: TTable;
	readonly returning: TReturning;
};

/**
 * The terminal insert stage: nothing left to chain but the compiled
 * query. `TTable` defaults to the widest `Table` and `TReturning` to
 * `undefined` (spec §5.2's "no projection = every column"), so every
 * existing non-generic consumer keeps compiling against the bare
 * `InsertFinal` name unchanged.
 */
export type InsertFinal<
	TTable extends Table = Table,
	TReturning extends ReturningProjection | undefined = undefined,
> = {
	readonly insertQuery: InsertNode;
	/** Type-only marker, never assigned — see {@link mutationStageBrand}. */
	readonly [mutationStageBrand]?: MutationStageMeta<TTable, TReturning>;
};
export type InsertReturnable<TTable extends Table = Table> =
	InsertFinal<TTable> & {
		/**
		 * No-arg = every column, snake_cased and explicit (spec §5.2); an
		 * object projection = exactly those aliased expressions. `TProjection`
		 * is inferred from the call site — omitted vs. supplied resolve to two
		 * different `InsertFinal` instantiations (task 4.11-mutation), not the
		 * same erased shape either way.
		 */
		returning<TProjection extends ReturningProjection | undefined = undefined>(
			projection?: TProjection,
		): InsertFinal<TTable, TProjection>;
	};
export type InsertConflictable<TTable extends Table> =
	InsertReturnable<TTable> & {
		onConflictDoNothing(
			...targetColumns: ReadonlyArray<ColumnRef>
		): InsertReturnable<TTable>;
		onConflictDoUpdate(config: {
			readonly target: ReadonlyArray<ColumnRef>;
			readonly set: MutationRow<TTable>;
		}): InsertReturnable<TTable>;
	};

export type UpdateFinal<
	TTable extends Table = Table,
	TReturning extends ReturningProjection | undefined = undefined,
> = {
	readonly updateQuery: UpdateNode;
	/** Type-only marker, never assigned — see {@link mutationStageBrand}. */
	readonly [mutationStageBrand]?: MutationStageMeta<TTable, TReturning>;
};
export type UpdateReturnable<TTable extends Table = Table> =
	UpdateFinal<TTable> & {
		returning<TProjection extends ReturningProjection | undefined = undefined>(
			projection?: TProjection,
		): UpdateFinal<TTable, TProjection>;
	};
export type UpdateFilterable<TTable extends Table = Table> =
	UpdateReturnable<TTable> & {
		where(condition: Condition): UpdateReturnable<TTable>;
	};

export type DeleteFinal<
	TTable extends Table = Table,
	TReturning extends ReturningProjection | undefined = undefined,
> = {
	readonly deleteQuery: DeleteNode;
	/** Type-only marker, never assigned — see {@link mutationStageBrand}. */
	readonly [mutationStageBrand]?: MutationStageMeta<TTable, TReturning>;
};
export type DeleteReturnable<TTable extends Table = Table> =
	DeleteFinal<TTable> & {
		returning<TProjection extends ReturningProjection | undefined = undefined>(
			projection?: TProjection,
		): DeleteFinal<TTable, TProjection>;
	};
export type DeleteFilterable<TTable extends Table = Table> =
	DeleteReturnable<TTable> & {
		where(condition: Condition): DeleteReturnable<TTable>;
	};

/**
 * `MutationRow<TTable>`/row objects are keyed by a table's own TypeScript
 * column names — a generic mapped type TypeScript can't trace back through
 * runtime key lookup. This is this file's one generic/runtime boundary
 * crossing (mirrors `dsl/table.ts`'s Task 7 cast, same underlying reason):
 * `Table`'s own enumerable properties are always its column `ColumnRef`s
 * (Task 7), so a plain-record view here is safe.
 */
const asRecord = (value: unknown): Record<string, unknown> =>
	value as Record<string, unknown>;

const isColumnRef = (value: unknown): value is ColumnRef =>
	isExpr(value) && "sqlName" in value;

const resolveTableRef = (target: Table): TableRefNode => {
	const meta = getTableMeta(target);
	return { schemaName: meta.schema.schemaName, tableName: meta.tableName };
};

/** Postgres rejects `on conflict ()` at parse time, so an empty target must fail here, not compile. */
const resolveConflictTarget = (
	targetColumns: ReadonlyArray<ColumnRef>,
): ReadonlyArray<string> => {
	if (targetColumns.length === 0) {
		return throwHejbroError(
			"empty-conflict-target",
			"onConflictDoNothing()/onConflictDoUpdate() received no conflict target columns — Postgres rejects `on conflict ()`. Next: name at least one declared column of the inserted table, e.g. onConflictDoNothing(posts.slug).",
		);
	}
	return targetColumns.map((column) => column.sqlName);
};

const resolveColumnRef = (
	target: Table,
	tableRef: TableRefNode,
	key: string,
): ColumnRef => {
	const column = asRecord(target)[key];
	if (!isColumnRef(column)) {
		return throwHejbroError(
			"unknown-column",
			`insert()/update() on "${tableRef.schemaName}.${tableRef.tableName}" received unknown column key "${key}". Next: use a column key declared on this table's table() call — this is usually a typo in "${key}", or a column that was never declared on this table.`,
		);
	}
	return column;
};

const allColumnsReturning = (target: Table): ReturningNode => ({
	returningKind: "allColumns",
	columnNames: getTableMeta(target).columns.map((column) => column.columnName),
});

const resolveReturning = (
	target: Table,
	projection?: ReturningProjection,
): ReturningNode => {
	if (projection === undefined) {
		return allColumnsReturning(target);
	}
	const entries = Object.entries(projection);
	if (entries.length === 0) {
		return throwHejbroError(
			"empty-returning",
			"returning({}) has no columns — an empty returning clause is not valid SQL. Next: pass at least one aliased expression, e.g. returning({ id: posts.id }), or call returning() with no argument for every column.",
		);
	}
	return {
		returningKind: "columns",
		// Same split as select()'s projection (#339): `alias` is the rendered
		// snake label, `resultKey` the caller's verbatim TS key for row
		// conversion -- never rendered, never stored.
		columns: entries.map(([alias, value]) => ({
			alias: toSnakeCase(alias),
			resultKey: alias,
			expr: value.exprNode,
		})),
	};
};

const resolveSetEntries = (
	target: Table,
	tableRef: TableRefNode,
	values: unknown,
): ReadonlyArray<{ readonly columnName: string; readonly value: ExprNode }> => {
	const record = asRecord(values);
	const keys = Object.keys(record);
	if (keys.length === 0) {
		return throwHejbroError(
			"empty-set",
			"set()/values() received no columns. Next: declare at least one column to write.",
		);
	}
	return keys.map((key) => {
		const column = resolveColumnRef(target, tableRef, key);
		return {
			columnName: column.sqlName,
			value: liftColumnValue(record[key], column.typeNode),
		};
	});
};

/** Internal-only `default` marker for a multi-row insert's missing keys — never constructed from user input (D18's `sql.raw` remains the only user-facing raw-SQL escape hatch). */
const defaultValueNode: ExprNode = { nodeKind: "rawSql", sql: "default" };

const collectColumnKeys = (
	rows: ReadonlyArray<Record<string, unknown>>,
): ReadonlyArray<string> => {
	const allKeys = rows.flatMap((row) => Object.keys(row));
	return allKeys.filter((key, index) => allKeys.indexOf(key) === index);
};

const normalizeRows = (
	rowsInput: unknown,
): ReadonlyArray<Record<string, unknown>> => {
	if (Array.isArray(rowsInput)) {
		return rowsInput.map(asRecord);
	}
	return [asRecord(rowsInput)];
};

const valueAtKey = (
	row: Record<string, unknown>,
	key: string | undefined,
): unknown => {
	if (key === undefined) {
		return undefined;
	}
	return row[key];
};

const resolveInsertRows = (
	target: Table,
	tableRef: TableRefNode,
	rowsInput: unknown,
): {
	readonly columnNames: ReadonlyArray<string>;
	readonly rows: ReadonlyArray<ReadonlyArray<ExprNode>>;
} => {
	const rows = normalizeRows(rowsInput);

	const keys = collectColumnKeys(rows);
	if (keys.length === 0) {
		return throwHejbroError(
			"empty-set",
			"set()/values() received no columns. Next: declare at least one column to write.",
		);
	}

	const columns = keys.map((key) => resolveColumnRef(target, tableRef, key));
	const columnNames = columns.map((column) => column.sqlName);

	const resolvedRows = rows.map((row) =>
		columns.map((column, index) => {
			const value = valueAtKey(row, keys[index]);
			if (value === undefined) {
				return defaultValueNode;
			}
			return liftColumnValue(value, column.typeNode);
		}),
	);

	return { columnNames, rows: resolvedRows };
};

/**
 * `insertQuery` is the same plain runtime node for any `TTable`/
 * `TReturning` — the cast at each of these factories' own return is
 * exactly {@link mutationStageBrand}'s own promise: the phantom key is
 * never actually set, so a real object without it is safe to narrow to
 * whichever instantiation the caller asked for (same reasoning as
 * `dsl/define-function.ts`'s `defineFunction` return and `compile.ts`'s
 * `handler` cast, g2).
 */
const makeInsertFinal = <
	TTable extends Table = Table,
	TReturning extends ReturningProjection | undefined = undefined,
>(
	node: InsertNode,
): InsertFinal<TTable, TReturning> =>
	({ insertQuery: node }) as InsertFinal<TTable, TReturning>;

const makeInsertReturnable = <TTable extends Table>(
	node: InsertNode,
	target: TTable,
): InsertReturnable<TTable> => {
	const derive = (next: InsertNode) => {
		noteBuilder(next, node);
		return makeInsertFinal(next);
	};
	const stage = {
		insertQuery: node,
		returning: (projection?: ReturningProjection) =>
			derive({
				...node,
				returning: resolveReturning(target, projection),
			}),
	};
	return stage as InsertReturnable<TTable>;
};

const makeInsertConflictable = <TTable extends Table>(
	node: InsertNode,
	target: TTable,
): InsertConflictable<TTable> => {
	const deriveFinal = (next: InsertNode) => {
		noteBuilder(next, node);
		return makeInsertFinal(next);
	};
	const deriveReturnable = (next: InsertNode) => {
		noteBuilder(next, node);
		return makeInsertReturnable(next, target);
	};
	const stage = {
		insertQuery: node,
		returning: (projection?: ReturningProjection) =>
			deriveFinal({
				...node,
				returning: resolveReturning(target, projection),
			}),
		onConflictDoNothing: (...targetColumns: ReadonlyArray<ColumnRef>) =>
			deriveReturnable({
				...node,
				onConflict: {
					targetColumns: resolveConflictTarget(targetColumns),
					action: { actionKind: "nothing" },
				},
			}),
		onConflictDoUpdate: (config: {
			readonly target: ReadonlyArray<ColumnRef>;
			readonly set: MutationRow<TTable>;
		}) => {
			const tableRef = resolveTableRef(target);
			return deriveReturnable({
				...node,
				onConflict: {
					targetColumns: resolveConflictTarget(config.target),
					action: {
						actionKind: "update",
						set: resolveSetEntries(target, tableRef, config.set),
					},
				},
			});
		},
	};
	return stage as InsertConflictable<TTable>;
};

/** Starts an insert into `target` — chain `.values(row | rows)`. */
export const insert = <TTable extends Table>(
	target: TTable,
): {
	values(
		rows: MutationRow<TTable> | ReadonlyArray<MutationRow<TTable>>,
	): InsertConflictable<TTable>;
} => ({
	values: (rows) => {
		const tableRef = resolveTableRef(target);
		const { columnNames, rows: resolvedRows } = resolveInsertRows(
			target,
			tableRef,
			rows,
		);
		const node: InsertNode = {
			queryKind: "insert",
			table: tableRef,
			columnNames,
			rows: resolvedRows,
			onConflict: null,
			returning: null,
		};
		noteBuilder(node, null);
		return makeInsertConflictable(node, target);
	},
});

const makeUpdateFinal = <
	TTable extends Table = Table,
	TReturning extends ReturningProjection | undefined = undefined,
>(
	node: UpdateNode,
): UpdateFinal<TTable, TReturning> =>
	({ updateQuery: node }) as UpdateFinal<TTable, TReturning>;

const makeUpdateReturnable = <TTable extends Table>(
	node: UpdateNode,
	target: TTable,
): UpdateReturnable<TTable> => {
	const derive = (next: UpdateNode) => {
		noteBuilder(next, node);
		return makeUpdateFinal(next);
	};
	const stage = {
		updateQuery: node,
		returning: (projection?: ReturningProjection) =>
			derive({
				...node,
				returning: resolveReturning(target, projection),
			}),
	};
	return stage as UpdateReturnable<TTable>;
};

const makeUpdateFilterable = <TTable extends Table>(
	node: UpdateNode,
	target: TTable,
): UpdateFilterable<TTable> => {
	const deriveFinal = (next: UpdateNode) => {
		noteBuilder(next, node);
		return makeUpdateFinal(next);
	};
	const deriveReturnable = (next: UpdateNode) => {
		noteBuilder(next, node);
		return makeUpdateReturnable(next, target);
	};
	const stage = {
		updateQuery: node,
		returning: (projection?: ReturningProjection) =>
			deriveFinal({
				...node,
				returning: resolveReturning(target, projection),
			}),
		where: (condition: Condition) =>
			deriveReturnable({ ...node, where: condition.exprNode }),
	};
	return stage as UpdateFilterable<TTable>;
};

/** Starts an update of `target` — chain `.set(values)`. */
export const update = <TTable extends Table>(
	target: TTable,
): { set(values: MutationRow<TTable>): UpdateFilterable<TTable> } => ({
	set: (values) => {
		const tableRef = resolveTableRef(target);
		const node: UpdateNode = {
			queryKind: "update",
			table: tableRef,
			set: resolveSetEntries(target, tableRef, values),
			where: null,
			returning: null,
		};
		noteBuilder(node, null);
		return makeUpdateFilterable(node, target);
	},
});

const makeDeleteFinal = <
	TTable extends Table = Table,
	TReturning extends ReturningProjection | undefined = undefined,
>(
	node: DeleteNode,
): DeleteFinal<TTable, TReturning> =>
	({ deleteQuery: node }) as DeleteFinal<TTable, TReturning>;

const makeDeleteReturnable = <TTable extends Table>(
	node: DeleteNode,
	target: TTable,
): DeleteReturnable<TTable> => {
	const derive = (next: DeleteNode) => {
		noteBuilder(next, node);
		return makeDeleteFinal(next);
	};
	const stage = {
		deleteQuery: node,
		returning: (projection?: ReturningProjection) =>
			derive({
				...node,
				returning: resolveReturning(target, projection),
			}),
	};
	return stage as DeleteReturnable<TTable>;
};

const makeDeleteFilterable = <TTable extends Table>(
	node: DeleteNode,
	target: TTable,
): DeleteFilterable<TTable> => {
	const deriveFinal = (next: DeleteNode) => {
		noteBuilder(next, node);
		return makeDeleteFinal(next);
	};
	const deriveReturnable = (next: DeleteNode) => {
		noteBuilder(next, node);
		return makeDeleteReturnable(next, target);
	};
	const stage = {
		deleteQuery: node,
		returning: (projection?: ReturningProjection) =>
			deriveFinal({
				...node,
				returning: resolveReturning(target, projection),
			}),
		where: (condition: Condition) =>
			deriveReturnable({ ...node, where: condition.exprNode }),
	};
	return stage as DeleteFilterable<TTable>;
};

/** Starts a delete from `target` (`deleteFrom` — `delete` is a reserved word). */
export const deleteFrom = <TTable extends Table>(
	target: TTable,
): DeleteFilterable<TTable> => {
	const tableRef = resolveTableRef(target);
	const node: DeleteNode = {
		queryKind: "delete",
		table: tableRef,
		where: null,
		returning: null,
	};
	noteBuilder(node, null);
	return makeDeleteFilterable(node, target);
};
