import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { throwHejbroError } from "@hejbro/core";

/** Every synced module's header carries this line verbatim — the mark
 * {@link assertSafeToOverwrite} checks for before writing over an
 * existing file (schema-sync delta, "A file that is not a synced module
 * is not overwritten"). A textual mark, not an executed one: checking it
 * never needs to load the existing file as code, which a hand-written or
 * unrelated file at the destination might not even be. */
export const SYNCED_MODULE_MARKER =
	"// Generated by `hejbro sync` — do not edit by hand.";

/** Whether `text` carries a synced module's own mark. */
export const isSyncedModuleText = (text: string): boolean =>
	text.includes(SYNCED_MODULE_MARKER);

/**
 * Refuses to write `source` over an existing file at `destinationPath`
 * unless that file already carries a synced module's own mark, or the
 * caller passed `force` — naming the path and both ways forward, per the
 * delta's own text. Writing nothing and refusing loudly is the same
 * silent-wrong-answer risk this whole capability exists to remove,
 * moved from a type to a working tree.
 */
export const writeSyncedModule = (
	destinationPath: string,
	source: string,
	force: boolean,
): void => {
	if (existsSync(destinationPath) && !force) {
		const existingText = readFileSync(destinationPath, "utf8");
		if (!isSyncedModuleText(existingText)) {
			throwHejbroError(
				"sync-destination-not-synced",
				`"${destinationPath}" already exists and doesn't look like a file \`hejbro sync\` wrote. Next: point --out at a different destination, or pass --force if overwriting it is what you want.`,
			);
		}
	}
	writeFileSync(destinationPath, source);
};
